---@module 'lazy'
return { ---@type LazySpec
  'NeogitOrg/neogit',
  cmd = 'Neogit',
  version = false,
  dependencies = {
    'sindrets/diffview.nvim',
    'esmuellert/codediff.nvim',
    'm00qek/baleia.nvim',
    'nvim-telescope/telescope.nvim',
    'ibhagwan/fzf-lua',
    'nvim-mini/mini.pick',
    'folke/snacks.nvim',
  },
  keys = { { '<leader>Gg', '<CMD>Neogit<CR>', desc = 'Show Neogit UI' } },
  cond = require('user_api').check.executable('git'),
  config = function()
    require('neogit').setup({
      auto_close_console = true,
      auto_refresh = true,
      auto_show_console = true,
      commit_order = 'topo',
      console_timeout = 2000,
      disable_context_highlighting = false,
      disable_hint = false,
      disable_insert_on_commit = 'auto',
      disable_line_numbers = true,
      disable_relative_line_numbers = true,
      disable_signs = false,
      filewatcher = { enabled = true, interval = 1000 },
      floating = { border = 'rounded', height = 0.7, relative = 'editor', style = 'minimal', width = 0.8 },
      git_executable = 'git',
      graph_style = 'ascii',
      highlight = { bold = true, italic = true, underline = true },
      ignored_settings = {},
      initial_branch_name = '',
      kind = 'tab',
      notification_icon = '󰊢',
      process_spinner = false,
      prompt_amend_commit = true,
      prompt_force_push = true,
      remember_settings = true,
      sort_branches = '-committerdate',
      treesitter_diff_highlight = true,
      use_default_keymaps = true,
      use_per_project_settings = true,
      word_diff_highlight = true,
      status = {
        HEAD_folded = false,
        HEAD_padding = 10,
        mode_padding = 3,
        mode_text = {
          A = 'added',
          AA = 'unmerged',
          AU = 'unmerged',
          C = 'copied',
          D = 'deleted',
          DD = 'unmerged',
          DU = 'unmerged',
          M = 'modified',
          N = 'new file',
          R = 'renamed',
          T = 'changed',
          U = 'updated',
          UA = 'unmerged',
          UD = 'unmerged',
          UU = 'unmerged',
          ['?'] = '',
        },
        recent_commit_count = 10,
        show_head_commit_hash = true,
      },
      commit_editor = {
        kind = 'tab',
        show_staged_diff = true,
        spell_check = true,
        staged_diff_split_kind = 'split',
      },
      commit_select_view = { kind = 'tab' },
      commit_view = { kind = 'vsplit', verify_commit = vim.fn.executable('gpg') == 1 },
      log_view = { kind = 'tab' },
      rebase_editor = { kind = 'auto' },
      reflog_view = { kind = 'tab' },
      merge_editor = { kind = 'auto' },
      preview_buffer = { kind = 'floating_console' },
      popup = { kind = 'popup', show_title = false },
      stash = { kind = 'tab' },
      refs_view = { kind = 'tab' },
      signs = { hunk = { '', '' }, item = { '>', 'v' }, section = { '>', 'v' } },
      sections = {
        rebase = { folded = true, hidden = false },
        recent = { folded = true, hidden = false },
        sequencer = { folded = false, hidden = false },
        staged = { folded = false, hidden = false },
        stashes = { folded = true, hidden = false },
        unmerged_pushRemote = { folded = false, hidden = false },
        unmerged_upstream = { folded = false, hidden = false },
        unpulled_pushRemote = { folded = true, hidden = false },
        unpulled_upstream = { folded = true, hidden = false },
        unstaged = { folded = false, hidden = false },
        untracked = { folded = false, hidden = false },
      },
      mappings = {
        commit_editor = {
          ['<C-c><C-c>'] = 'Submit',
          ['<C-c><C-k>'] = 'Abort',
          ['<M-n>'] = 'NextMessage',
          ['<M-p>'] = 'PrevMessage',
          ['<M-r>'] = 'ResetMessage',
          q = 'Close',
        },
        commit_editor_I = { ['<C-c><C-c>'] = 'Submit', ['<C-c><C-k>'] = 'Abort' },
        rebase_editor = {
          ['<C-c><C-c>'] = 'Submit',
          ['<C-c><C-k>'] = 'Abort',
          ['<CR>'] = 'OpenCommit',
          ['[c'] = 'OpenOrScrollUp',
          [']c'] = 'OpenOrScrollDown',
          b = 'Break',
          d = 'Drop',
          e = 'Edit',
          f = 'Fixup',
          gj = 'MoveDown',
          gk = 'MoveUp',
          p = 'Pick',
          q = 'Close',
          r = 'Reword',
          s = 'Squash',
          x = 'Execute',
        },
        rebase_editor_I = { ['<C-c><C-c>'] = 'Submit', ['<C-c><C-k>'] = 'Abort' },
        finder = {
          ['<2-LeftMouse>'] = 'NOP',
          ['<C-c>'] = 'Close',
          ['<C-j>'] = 'NOP',
          ['<C-n>'] = 'Next',
          ['<C-p>'] = 'Previous',
          ['<C-y>'] = 'CopySelection',
          ['<CR>'] = 'Select',
          ['<Down>'] = 'Next',
          ['<Esc>'] = 'Close',
          ['<LeftMouse>'] = 'MouseClick',
          ['<S-Space>'] = 'MultiselectTogglePrevious',
          ['<ScrollWheelDown>'] = 'ScrollWheelDown',
          ['<ScrollWheelLeft>'] = 'NOP',
          ['<ScrollWheelRight>'] = 'NOP',
          ['<ScrollWheelUp>'] = 'ScrollWheelUp',
          ['<Space>'] = 'MultiselectToggleNext',
          ['<Tab>'] = 'InsertCompletion',
          ['<Up>'] = 'Previous',
        },
        popup = {
          A = 'CherryPickPopup',
          B = 'BisectPopup',
          M = 'RemotePopup',
          P = 'PushPopup',
          X = 'ResetPopup',
          Z = 'StashPopup',
          ['?'] = 'HelpPopup',
          b = 'BranchPopup',
          c = 'CommitPopup',
          d = 'DiffPopup',
          f = 'FetchPopup',
          i = 'IgnorePopup',
          l = 'LogPopup',
          m = 'MergePopup',
          p = 'PullPopup',
          r = 'RebasePopup',
          t = 'TagPopup',
          v = 'RevertPopup',
          w = 'WorktreePopup',
        },
        status = {
          I = 'InitRepo',
          K = 'Untrack',
          Q = 'Command',
          S = 'StageUnstaged',
          U = 'UnstageStaged',
          Y = 'YankSelected',
          ['$'] = 'CommandHistory',
          ['1'] = 'Depth1',
          ['2'] = 'Depth2',
          ['3'] = 'Depth3',
          ['4'] = 'Depth4',
          ['<C-j>'] = 'PeekDown',
          ['<C-k>'] = 'PeekUp',
          ['<C-n>'] = 'NextSection',
          ['<C-p>'] = 'PreviousSection',
          ['<C-r>'] = 'RefreshBuffer',
          ['<C-s>'] = 'StageAll',
          ['<C-t>'] = 'TabOpen',
          ['<C-v>'] = 'VSplitOpen',
          ['<C-x>'] = 'SplitOpen',
          ['<CR>'] = 'GoToFile',
          ['<S-cr>'] = 'PeekFile',
          ['<Tab>'] = 'Toggle',
          ['[c'] = 'OpenOrScrollUp',
          [']c'] = 'OpenOrScrollDown',
          ['{'] = 'GoToPreviousHunkHeader',
          ['}'] = 'GoToNextHunkHeader',
          gp = 'GoToParentRepo',
          j = 'MoveDown',
          k = 'MoveUp',
          o = 'OpenTree',
          q = 'Close',
          s = 'Stage',
          u = 'Unstage',
          x = 'Discard',
          y = 'ShowRefs',
          za = 'Toggle',
          zo = 'OpenFold',
        },
      },
      telescope_sorter = function()
        return require('telescope').extensions.fzf.native_fzf_sorter()
      end,
    })
  end,
}
-- vim: set ts=2 sts=2 sw=2 et ai si sta:
