---@module 'lazy'
local ensure_langs = { ---@type string[]
  'arduino',
  'asm',
  'awk',
  'bash',
  'bibtex',
  'c',
  'c_sharp',
  'cmake',
  'comment',
  'commonlisp',
  'cpp',
  'css',
  'csv',
  'desktop',
  'diff',
  'dockerfile',
  'doxygen',
  'dtd',
  'editorconfig',
  'fennel',
  'git_config',
  'git_rebase',
  'gitattributes',
  'gitignore',
  'go',
  'gpg',
  'haskell',
  'haskell_persistent',
  'hcl',
  'html',
  'html_tags',
  'hyprlang',
  'ini',
  'java',
  'javadoc',
  'javascript',
  'jsdoc',
  'json',
  'json5',
  'julia',
  'kconfig',
  'kitty',
  'lua',
  'luadoc',
  'luap',
  'luau',
  'make',
  'markdown',
  'markdown_inline',
  'meson',
  'nginx',
  'ninja',
  'nix',
  'passwd',
  'perl',
  'php',
  'php_only',
  'powershell',
  'printf',
  'properties',
  'python',
  'query',
  'readline',
  'regex',
  'requirements',
  'rst',
  'ruby',
  'rust',
  'scheme',
  'scss',
  'sql',
  'ssh_config',
  'templ',
  'todotxt',
  'toml',
  'typescript',
  'udev',
  'vim',
  'vimdoc',
  'xcompose',
  'xml',
  'xresources',
  'yaml',
  'zig',
  'zsh',
}
local patterns = { ---@type string[]
  'arduino',
  'asm',
  'awk',
  'bash',
  'bib',
  'c',
  'cmake',
  'cpp',
  'cs',
  'css',
  'csv',
  'diff',
  'dosini',
  'editorconfig',
  'gitattributes',
  'gitconfig',
  'gitignore',
  'gitrebase',
  'gpg',
  'haskell',
  'hcl',
  'html',
  'hyprlang',
  'java',
  'javascript',
  'javascriptreact',
  'json',
  'json5',
  'julia',
  'kitty',
  'lua',
  'luau',
  'markdown',
  'meson',
  'ninja',
  'nginx',
  'passwd',
  'python',
  'query',
  'readline',
  'regex',
  'requirements',
  'rust',
  'scss',
  'sh',
  'sql',
  'sshconfig',
  'template',
  'toml',
  'typescript',
  'udevconf',
  'udevrules',
  'vim',
  'xml',
  'yaml',
  'zig',
  'zsh',
}

if not require('user_api').distro.termux.is_distro() then
  table.insert(ensure_langs, 'gitcommit')
  table.insert(ensure_langs, 'latex')
  table.insert(patterns, 'gitcommit')
  table.insert(patterns, 'tex')
end

return { ---@type LazySpec
  'nvim-treesitter/nvim-treesitter',
  branch = 'main',
  build = ':TSUpdate',
  config = function()
    require('nvim-treesitter.config').setup({ install_dir = vim.fs.joinpath(vim.fn.stdpath('data'), 'site') })
    require('nvim-treesitter.install').install(ensure_langs)

    vim.api.nvim_create_autocmd('FileType', {
      group = vim.api.nvim_create_augroup('TsInstall', { clear = true }),
      pattern = patterns,
      callback = function(ev)
        vim.treesitter.start()

        vim.bo[ev.buf].indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
      end,
    })

    vim.api.nvim_create_autocmd('User', {
      pattern = 'TSUpdate',
      callback = function()
        require('nvim-treesitter.parsers').lua.install_info.generate = true
      end,
    })
  end,
}
-- vim: set ts=2 sts=2 sw=2 et ai si sta:
