---@module 'lazy'
local ensure_langs = { ---@type string[]
  'arduino',
  'asm',
  'awk',
  'bash',
  'bibtex',
  'c',
  'c_sharp',
  'cmake',
  'comment',
  'commonlisp',
  'cpp',
  'css',
  'csv',
  'desktop',
  'diff',
  'dockerfile',
  'doxygen',
  'dtd',
  'editorconfig',
  'fennel',
  'ghostty',
  'git_config',
  'git_rebase',
  'gitattributes',
  'gitignore',
  'go',
  'gpg',
  'haskell',
  'haskell_persistent',
  'hcl',
  'html',
  'html_tags',
  'hyprlang',
  'ini',
  'java',
  'javadoc',
  'javascript',
  'jsdoc',
  'json',
  'json5',
  'julia',
  'kconfig',
  'kitty',
  'lua',
  'luadoc',
  'luap',
  'luau',
  'make',
  'markdown',
  'markdown_inline',
  'meson',
  'nginx',
  'ninja',
  'nix',
  'passwd',
  'perl',
  'php',
  'php_only',
  'powershell',
  'printf',
  'properties',
  'python',
  'query',
  'readline',
  'regex',
  'requirements',
  'rst',
  'ruby',
  'rust',
  'scheme',
  'scss',
  'sql',
  'ssh_config',
  'templ',
  'tmux',
  'todotxt',
  'toml',
  'typescript',
  'udev',
  'vim',
  'vimdoc',
  'xcompose',
  'xml',
  'xresources',
  'yaml',
  'zathurarc',
  'zig',
  'zsh',
}
local patterns = { ---@type string[]
  'arduino',
  'asm',
  'awk',
  'bash',
  'bib',
  'c',
  'cmake',
  'cpp',
  'cs',
  'css',
  'csv',
  'diff',
  'dosini',
  'editorconfig',
  'ghostty',
  'gitattributes',
  'gitconfig',
  'gitignore',
  'gitrebase',
  'gpg',
  'haskell',
  'hcl',
  'html',
  'hyprlang',
  'java',
  'javascript',
  'javascriptreact',
  'json',
  'json5',
  'julia',
  'kitty',
  'lua',
  'luau',
  'markdown',
  'meson',
  'ninja',
  'nginx',
  'passwd',
  'python',
  'query',
  'readline',
  'regex',
  'requirements',
  'rust',
  'scss',
  'sh',
  'sql',
  'sshconfig',
  'template',
  'tmux',
  'toml',
  'typescript',
  'udevconf',
  'udevrules',
  'vim',
  'xml',
  'yaml',
  'zathurarc',
  'zig',
  'zsh',
}

if not require('user_api').distro.termux.is_distro() then
  table.insert(ensure_langs, 'gitcommit')
  table.insert(ensure_langs, 'latex')
  table.insert(patterns, 'gitcommit')
  table.insert(patterns, 'tex')
end

return { ---@type LazySpec
  'romus204/tree-sitter-manager.nvim',
  config = function()
    require('tree-sitter-manager').setup({
      parser_dir = vim.fs.joinpath(vim.fn.stdpath('data'), 'site/parser'),
      query_dir = vim.fs.joinpath(vim.fn.stdpath('data'), 'site/queries'),
      assume_installed = {},
      ensure_installed = ensure_langs,
      border = 'rounded',
      auto_install = true,
      noauto_install = {},
      highlight = true,
      nohighlight = {},
      languages = {},
      nerdfont = true,
    })

    local group = vim.api.nvim_create_augroup('TSPlugin', { clear = true })
    vim.api.nvim_create_autocmd('FileType', {
      group = group,
      pattern = patterns,
      callback = function(ev)
        if not vim.api.nvim_buf_is_loaded(ev.buf) then
          return
        end
        local lang = vim.treesitter.language.get_lang(vim.api.nvim_get_option_value('filetype', { buf = ev.buf }))
        if not (lang and vim.treesitter.language.add(lang)) then
          return
        end
        vim.treesitter.language.register('bash', { 'sh' })
        vim.treesitter.start(ev.buf)
      end,
    })
  end,
}
-- vim: set ts=2 sts=2 sw=2 et ai si sta:
