---@module 'lazy'
---@module 'render-markdown'
return { ---@type LazySpec
  'MeanderingProgrammer/render-markdown.nvim',
  dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-mini/mini.nvim' },
  cond = not require('user_api').check.in_console() and require('user_api').check.executable('tree-sitter'),
  opts = { ---@type render.md.UserConfig
    anti_conceal = {
      enabled = true,
      disabled_modes = false,
      above = 0,
      below = 0,
      ignore = { code_background = true, indent = true, sign = true, virtual_lines = true },
    },
    callout = {
      abstract = {
        category = 'obsidian',
        highlight = 'RenderMarkdownInfo',
        raw = '[!ABSTRACT]',
        rendered = '󰨸 Abstract',
      },
      attention = {
        category = 'obsidian',
        highlight = 'RenderMarkdownWarn',
        raw = '[!ATTENTION]',
        rendered = '󰀪 Attention',
      },
      bug = { category = 'obsidian', highlight = 'RenderMarkdownError', raw = '[!BUG]', rendered = '󰨰 Bug' },
      caution = {
        category = 'github',
        highlight = 'RenderMarkdownError',
        raw = '[!CAUTION]',
        rendered = '󰳦 Caution',
      },
      check = { category = 'obsidian', highlight = 'RenderMarkdownSuccess', raw = '[!CHECK]', rendered = '󰄬 Check' },
      cite = { category = 'obsidian', highlight = 'RenderMarkdownQuote', raw = '[!CITE]', rendered = '󱆨 Cite' },
      danger = {
        category = 'obsidian',
        highlight = 'RenderMarkdownError',
        raw = '[!DANGER]',
        rendered = '󱐌 Danger',
      },
      done = { category = 'obsidian', highlight = 'RenderMarkdownSuccess', raw = '[!DONE]', rendered = '󰄬 Done' },
      error = { category = 'obsidian', highlight = 'RenderMarkdownError', raw = '[!ERROR]', rendered = '󱐌 Error' },
      example = {
        category = 'obsidian',
        highlight = 'RenderMarkdownHint',
        raw = '[!EXAMPLE]',
        rendered = '󰉹 Example',
      },
      fail = { category = 'obsidian', highlight = 'RenderMarkdownError', raw = '[!FAIL]', rendered = '󰅖 Fail' },
      failure = {
        category = 'obsidian',
        highlight = 'RenderMarkdownError',
        raw = '[!FAILURE]',
        rendered = '󰅖 Failure',
      },
      faq = { category = 'obsidian', highlight = 'RenderMarkdownWarn', raw = '[!FAQ]', rendered = '󰘥 Faq' },
      help = { category = 'obsidian', highlight = 'RenderMarkdownWarn', raw = '[!HELP]', rendered = '󰘥 Help' },
      hint = { category = 'obsidian', highlight = 'RenderMarkdownSuccess', raw = '[!HINT]', rendered = '󰌶 Hint' },
      important = {
        category = 'github',
        highlight = 'RenderMarkdownHint',
        raw = '[!IMPORTANT]',
        rendered = '󰅾 Important',
      },
      info = { category = 'obsidian', highlight = 'RenderMarkdownInfo', raw = '[!INFO]', rendered = '󰋽 Info' },
      missing = {
        category = 'obsidian',
        highlight = 'RenderMarkdownError',
        raw = '[!MISSING]',
        rendered = '󰅖 Missing',
      },
      note = { category = 'github', highlight = 'RenderMarkdownInfo', raw = '[!NOTE]', rendered = '󰋽 Note' },
      question = {
        category = 'obsidian',
        highlight = 'RenderMarkdownWarn',
        raw = '[!QUESTION]',
        rendered = '󰘥 Question',
      },
      quote = { category = 'obsidian', highlight = 'RenderMarkdownQuote', raw = '[!QUOTE]', rendered = '󱆨 Quote' },
      success = {
        category = 'obsidian',
        highlight = 'RenderMarkdownSuccess',
        raw = '[!SUCCESS]',
        rendered = '󰄬 Success',
      },
      summary = {
        category = 'obsidian',
        highlight = 'RenderMarkdownInfo',
        raw = '[!SUMMARY]',
        rendered = '󰨸 Summary',
      },
      tip = { category = 'github', highlight = 'RenderMarkdownSuccess', raw = '[!TIP]', rendered = '󰌶 Tip' },
      tldr = { category = 'obsidian', highlight = 'RenderMarkdownInfo', raw = '[!TLDR]', rendered = '󰨸 Tldr' },
      todo = { category = 'obsidian', highlight = 'RenderMarkdownInfo', raw = '[!TODO]', rendered = '󰗡 Todo' },
      warning = {
        category = 'github',
        highlight = 'RenderMarkdownWarn',
        raw = '[!WARNING]',
        rendered = '󰀪 Warning',
      },
    },
    completions = { lsp = { enabled = true } },
    debounce = 100,
    enabled = true,
    indent = {
      enabled = false,
      highlight = 'RenderMarkdownIndent',
      icon = '▎',
      per_level = 2,
      priority = 0,
      render_modes = false,
      skip_heading = false,
      skip_level = 1,
    },
    injections = {
      gitcommit = {
        enabled = true,
        query = [[((message) @injection.content
        (#set! injection.combined)
        (#set! injection.include-children)
        (#set! injection.language "markdown"))]],
      },
    },
    link = {
      custom = {
        apple = { pattern = 'apple%.com', icon = ' ' },
        discord = { pattern = 'discord%.com', icon = '󰙯 ' },
        github = { pattern = 'github%.com', icon = '󰊤 ' },
        gitlab = { pattern = 'gitlab%.com', icon = '󰮠 ' },
        google = { pattern = 'google%.com', icon = '󰊭 ' },
        hackernews = { pattern = 'ycombinator%.com', icon = ' ' },
        linkedin = { pattern = 'linkedin%.com', icon = '󰌻 ' },
        microsoft = { pattern = 'microsoft%.com', icon = ' ' },
        neovim = { pattern = 'neovim%.io', icon = ' ' },
        reddit = { pattern = 'reddit%.com', icon = '󰑍 ' },
        slack = { pattern = 'slack%.com', icon = '󰒱 ' },
        stackoverflow = { pattern = 'stackoverflow%.com', icon = '󰓌 ' },
        steam = { pattern = 'steampowered%.com', icon = ' ' },
        twitter = { pattern = 'x%.com', icon = ' ' },
        web = { pattern = '^http', icon = '󰖟 ' },
        wikipedia = { pattern = 'wikipedia%.org', icon = '󰖬 ' },
        youtube = { pattern = 'youtube[^.]*%.com', icon = '󰗃 ' },
        youtube_short = { pattern = 'youtu%.be', icon = '󰗃 ' },
      },
      email = '󰀓 ',
      enabled = true,
      footnote = { enabled = true, icon = '󰯔 ', prefix = '', suffix = '', superscript = true },
      highlight = 'RenderMarkdownLink',
      hyperlink = '󰌹 ',
      image = '󰥶 ',
      render_modes = false,
      wiki = { body = function() end, highlight = 'RenderMarkdownWikiLink', icon = '󱗖 ' },
    },
    markdown = {
      disable = true,
      directives = { { id = 17, name = 'conceal_lines' }, { id = 18, name = 'conceal_lines' } },
    },
    max_file_size = 10.0,
    overrides = { buflisted = {}, buftype = { nofile = { code = { left_pad = 0, right_pad = 0 } } }, filetype = {} },
    render_modes = { 'n', 'c', 't' },
    restart_highlighter = true,
    win_options = {
      concealcursor = { default = vim.o.concealcursor, rendered = '' },
      conceallevel = { default = vim.o.conceallevel, rendered = 3 },
    },
  },
}
-- vim: set ts=2 sts=2 sw=2 et ai si sta:
