---@module 'lazy'
return { ---@type LazySpec[]
  {
    'taigrr/cyberpunk.nvim',
    lazy = false,
    priority = 1000,
    config = function()
      require('cyberpunk').setup({
        bold_functions = true,
        bold_keywords = true,
        italic_comments = false,
        italic_keywords = false,
        transparent = false,
      })
    end,
  },
  {
    'serhez/teide.nvim',
    lazy = false,
    priority = 1000,
    config = function()
      require('teide').setup({
        cache = true,
        dim_inactive = false,
        light_brightness = 0.3,
        light_style = 'light',
        lualine_bold = false,
        plugins = { all = package.loaded.lazy ~= nil, auto = true },
        style = 'dimmed',
        styles = {
          comments = { italic = false },
          floats = 'dark',
          functions = { italic = false },
          keywords = { italic = false },
          sidebars = 'dark',
          variables = { italic = false },
        },
        terminal_colors = true,
        transparent = false,
      })
    end,
  },
  {
    'folke/tokyonight.nvim',
    lazy = false,
    priority = 1000,
    version = false,
    cond = not require('user_api').check.in_console(),
    config = function()
      require('tokyonight').setup({
        cache = true,
        hide_inactive_statusline = true,
        live_reload = true,
        lualine_bold = false,
        on_colors = function(colors)
          colors.error = '#df4f4f'
          colors.info = colors.teal
        end,
        on_highlights = function() end,
        plugins = { all = package.loaded.lazy ~= nil, auto = true },
        sidebars = {
          'NvimTree',
          'TelescopePrompt',
          'diffview',
          'help',
          'lazy',
          'neo-tree',
          'noice',
          'packer',
          'qf',
          'terminal',
          'toggleterm',
          'trouble',
          'vista_kind',
        },
        style = 'storm',
        styles = {
          comments = { italic = false },
          floats = 'dark',
          functions = { bold = true, italic = false },
          keywords = { italic = false, bold = true },
          sidebars = 'dark',
          variables = { italic = false },
        },
        terminal_colors = true,
        transparent = false,
        use_background = true,
      })
    end,
  },
  {
    'tiagovla/tokyodark.nvim',
    lazy = false,
    priority = 1000,
    version = false,
    cond = not require('user_api').check.in_console(),
    config = function()
      require('tokyodark').setup({
        custom_highlights = {},
        custom_palette = {},
        gamma = 1.00,
        styles = {
          comments = { italic = false },
          functions = { bold = true },
          identifiers = { bold = true, italic = false },
          keywords = { italic = false },
          variables = {},
        },
        terminal_colors = vim.o.termguicolors,
        transparent_background = false,
      })
    end,
  },
  {
    'darianmorat/gruvdark.nvim',
    lazy = false,
    priority = 1000,
    version = false,
    cond = not require('user_api').check.in_console(),
    config = function()
      require('gruvdark').setup({ colors = {}, highlights = {}, transparent = false })
    end,
  },
  {
    'catppuccin/nvim',
    lazy = false,
    name = 'catppuccin',
    priority = 1000,
    version = false,
    cond = not require('user_api').check.in_console(),
    config = function()
      require('catppuccin').setup({
        background = { light = 'latte', dark = 'mocha' },
        dim_inactive = { enabled = true, shade = 'dark', percentage = 0.20 },
        flavour = 'auto',
        float = { solid = true, transparent = true },
        no_bold = false,
        no_italic = true,
        no_underline = false,
        show_end_of_buffer = true,
        styles = {
          booleans = { 'bold' },
          comments = { 'altfont' },
          conditionals = { 'bold' },
          functions = { 'bold' },
          keywords = { 'altfont' },
          loops = { 'bold' },
          -- miscs = {}, -- Uncomment to turn off hard-coded styles
          numbers = { 'altfont' },
          operators = { 'altfont' },
          properties = { 'bold' },
          strings = { 'altfont' },
          types = { 'altfont' },
          variables = { 'altfont' },
        },
        term_colors = true,
        transparent_background = false,
        color_overrides = {},
        custom_highlights = function(colors)
          return {
            CmpBorder = { fg = colors.surface2 },
            NvimTreeNormal = { fg = colors.none },
            Pmenu = { bg = colors.none },
            TabLineSel = { bg = colors.pink },
          }
        end,
        integrations = {
          alpha = true,
          barbar = true,
          blink_cmp = { style = 'bordered' },
          cmp = false,
          diffview = true,
          fzf = true,
          gitsigns = true,
          headlines = false,
          indent_blankline = { enabled = true, scope_color = 'teal', colored_indent_levels = true },
          lsp_trouble = true,
          markdown = true,
          mini = { enabled = true, indentscope_color = 'lavender' },
          native_lsp = {
            enabled = true,
            inlay_hints = { background = true },
            underlines = {
              errors = { 'underdouble' },
              hints = { 'underline' },
              information = { 'underline' },
              ok = { 'underline' },
              warnings = { 'underline' },
            },
            virtual_text = {
              errors = { 'bold', 'underdouble' },
              hints = { 'bold', 'underline' },
              information = { 'altfont', 'underline' },
              ok = { 'bold' },
              warnings = { 'bold', 'underline' },
            },
          },
          neotree = true,
          noice = true,
          notify = true,
          nvimtree = false,
          rainbow_delimiters = true,
          render_markdown = true,
          telescope = true,
          treesitter = true,
          treesitter_context = true,
          which_key = true,
        },
      })
    end,
  },
  {
    'navarasu/onedark.nvim',
    lazy = false,
    priority = 1000,
    version = false,
    cond = not require('user_api').check.in_console(),
    config = function()
      require('onedark').setup({
        code_style = {
          booleans = 'bold',
          comments = 'altfont',
          conditionals = 'bold',
          functions = 'bold',
          keywords = 'bold',
          loops = 'bold',
          numbers = 'altfont',
          operators = 'altfont',
          properties = 'bold',
          strings = 'altfont',
          types = 'bold',
          variables = 'altfont',
        },
        diagnostics = { background = true, darker = true, undercurl = true },
        ending_tildes = true,
        lualine = { transparent = false },
        style = 'deep',
        term_colors = true,
        toggle_style_list = { 'deep', 'darker', 'warmer' },
        transparent = false,
      })
    end,
  },
  {
    'EdenEast/nightfox.nvim',
    lazy = false,
    priority = 1000,
    version = false,
    cond = not require('user_api').check.in_console(),
    config = function()
      local compile_path = vim.fn.stdpath('state') .. '/nightfox'
      require('nightfox').setup({
        options = {
          compile_path = compile_path,
          compile_file_suffix = '_compiled',
          transparent = false,
          terminal_colors = true,
          dim_inactive = false,
          module_default = false,
          colorblind = { enable = false },
          styles = {
            comments = 'altfont',
            conditionals = 'bold',
            constants = 'bold',
            functions = 'bold',
            keywords = 'bold',
            numbers = 'NONE',
            operators = 'NONE',
            preprocs = 'bold',
            strings = 'altfont',
            types = 'bold',
            variables = 'altfont',
          },
          inverse = { match_paren = false, visual = false, search = false },
          modules = {
            barbar = false,
            blink = true,
            coc = { enable = false, background = true },
            cmp = true,
            dashboard = true,
            diagnostic = { enable = true, background = true },
            fern = false,
            fidget = false,
            gitgutter = false,
            gitsigns = true,
            glyph_palette = true,
            hop = false,
            illuminate = false,
            indent_blanklines = true,
            lazy = true,
            leap = { enable = false, background = true, harsh = false },
            lsp_semantic_tokens = true,
            mini = true,
            native_lsp = { enable = true, background = true },
            notify = true,
            nvimtree = true,
            neotree = true,
            pounce = true,
            telescope = true,
            treesitter = true,
            whichkey = true,
          },
        },
      })
    end,
  },
  {
    'rebelot/kanagawa.nvim',
    lazy = false,
    priority = 1000,
    version = false,
    cond = not require('user_api').check.in_console(),
    config = function()
      require('kanagawa').setup({
        background = { dark = 'wave', light = 'lotus' },
        colors = { palette = {}, theme = { wave = {}, lotus = {}, dragon = {}, all = {} } },
        commentStyle = { italic = false },
        compile = true,
        dimInactive = not require('user_api').check.in_console(),
        functionStyle = { bold = true, italic = false },
        keywordStyle = { bold = true, italic = false },
        overrides = function(colors)
          local theme = colors.theme
          return {
            FloatBoarder = { bg = 'none' },
            FloatTitle = { bg = 'none' },
            LazyNormal = { bg = theme.ui.bg_m3, fg = theme.ui.fg_dim },
            MasonNormal = { bg = theme.ui.bg_m3, fg = theme.ui.fg_dim },
            NormalDark = { fg = theme.ui.fg_dim, bg = theme.ui.bg_m3 },
            NormalFloat = { bg = 'none' },
            TelescopePreviewBorder = { bg = theme.ui.bg_dim, fg = theme.ui.bg_dim },
            TelescopePreviewNormal = { bg = theme.ui.bg_dim },
            TelescopePromptBorder = { fg = theme.ui.bg_p1, bg = theme.ui.bg_p1 },
            TelescopePromptNormal = { bg = theme.ui.bg_p1 },
            TelescopeResultsBorder = { fg = theme.ui.bg_m1, bg = theme.ui.bg_m1 },
            TelescopeResultsNormal = { fg = theme.ui.fg_dim, bg = theme.ui.bg_m1 },
            TelescopeTitle = { fg = theme.ui.special, bold = true },
          }
        end,
        statementStyle = { bold = true, italic = false },
        terminalColors = true,
        transparent = false,
        typeStyle = { italic = false, bold = true },
        undercurl = not require('user_api').check.in_console(),
        theme = 'wave',
      })
    end,
  },
  {
    'vague-theme/vague.nvim',
    lazy = false,
    priority = 1000,
    version = false,
    cond = not require('user_api').check.in_console(),
    config = function()
      require('vague').setup({
        bold = true,
        colors = {
          bg = '#141415',
          builtin = '#b4d4cf',
          comment = '#606079',
          constant = '#aeaed1',
          delta = '#f3be7c',
          error = '#d8647e',
          fg = '#cdcdcd',
          floatBorder = '#878787',
          func = '#c48282',
          hint = '#7e98e8',
          inactiveBg = '#1c1c24',
          keyword = '#6e94b2',
          line = '#252530',
          number = '#e0a363',
          operator = '#90a0b5',
          parameter = '#bb9dbd',
          plus = '#7fa563',
          property = '#c3c3d5',
          search = '#405065',
          string = '#e8b589',
          type = '#9bb4bc',
          visual = '#333738',
          warning = '#f3be7c',
        },
        italic = false,
        plugins = {
          cmp = { match = 'bold', match_fuzzy = 'bold' },
          dashboard = { footer = 'none' },
          lsp = {
            diagnostic_error = 'bold',
            diagnostic_hint = 'none',
            diagnostic_info = 'bold',
            diagnostic_ok = 'none',
            diagnostic_warn = 'bold',
          },
          neotest = { focused = 'bold', adapter_name = 'bold' },
          telescope = { match = 'bold' },
        },
        style = {
          boolean = 'bold',
          builtin_constants = 'bold',
          builtin_functions = 'none',
          builtin_types = 'bold',
          builtin_variables = 'none',
          comments = 'none',
          conditionals = 'none',
          error = 'bold',
          float = 'none',
          functions = 'none',
          headings = 'bold',
          keyword_return = 'bold',
          keywords = 'bold',
          keywords_exception = 'bold',
          keywords_label = 'bold',
          keywords_loop = 'bold',
          number = 'none',
          operators = 'none',
          strings = 'none',
          variables = 'none',
        },
        transparent = false,
      })
    end,
  },
  {
    'Mofiqul/dracula.nvim',
    lazy = false,
    priority = 1000,
    version = false,
    cond = not require('user_api').check.in_console(),
    config = function()
      require('dracula').setup({
        italic_comment = false,
        lualine_bg_color = '#44475a',
        overrides = {},
        show_end_of_buffer = false,
        transparent_bg = false,
      })
    end,
  },
  {
    'ellisonleao/gruvbox.nvim',
    lazy = false,
    priority = 1000,
    version = false,
    cond = not require('user_api').check.in_console(),
    config = function()
      require('gruvbox').setup({
        bold = true,
        contrast = 'soft',
        dim_inactive = true,
        inverse = false,
        invert_intend_guides = false,
        invert_selection = false,
        invert_signs = false,
        invert_tabline = false,
        italic = { comments = false, emphasis = false, folds = false, operators = false, strings = false },
        strikethrough = true,
        terminal_colors = true,
        transparent_mode = false,
        undercurl = true,
        underline = true,
      })
    end,
  },
  {
    'pineapplegiant/spaceduck',
    lazy = false,
    priority = 1000,
    version = false,
    cond = not require('user_api').check.in_console(),
  },
}
-- vim: set ts=2 sts=2 sw=2 et ai si sta:
