---@module 'lazy'

return { ---@type LazySpec
  'ibhagwan/fzf-lua',
  version = false,
  dependencies = { 'nvim-tree/nvim-web-devicons', 'nvim-mini/mini.icons' },
  cond = require('user_api.check.exists').executable('fzf'),
  config = function()
    local actions = require('fzf-lua').actions
    actions = {
      files = {
        true,
        enter = actions.file_edit_or_qf,
        ['ctrl-s'] = actions.file_split,
        ['ctrl-v'] = actions.file_vsplit,
        ['ctrl-t'] = actions.file_tabedit,
        ['alt-q'] = actions.file_sel_to_qf,
        ['alt-Q'] = actions.file_sel_to_ll,
        ['alt-i'] = actions.toggle_ignore,
        ['alt-h'] = actions.toggle_hidden,
        ['alt-f'] = actions.toggle_follow,
      },
    }
    require('fzf-lua').setup({
      globals = { file_icon_padding = '', help_open_win = vim.api.nvim_open_win },
      defaults = { file_icons = 'mini', copen = 'topleft copen' },
      files = {
        previewer = 'bat',
        prompt = 'Files❯ ',
        multiprocess = true,
        git_icons = true,
        file_icons = true,
        color_icons = true,
        path_shorten = true,
        formatter = 'path.filename_first',
        cmd = 'rg --files',
        find_opts = [[-type f \! -path '*/.git/*']],
        rg_opts = [[--color=never --hidden --files -g "!.git"]],
        fd_opts = [[--color=never --hidden --type f --type l --exclude .git]],
        dir_opts = [[/s/b/a:-d]],
        cwd_header = true,
        cwd_prompt = true,
        cwd_prompt_shorten_len = 32,
        cwd_prompt_shorten_val = 1,
        toggle_ignore_flag = '--no-ignore',
        toggle_hidden_flag = '--hidden',
        toggle_follow_flag = '-L',
        hidden = true,
        follow = false,
        no_ignore = false,
        actions = { enter = actions.file_edit },
      },
      git = {
        files = {
          prompt = 'GitFiles❯ ',
          cmd = 'git ls-files --exclude-standard',
          multiprocess = true,
          git_icons = true,
          file_icons = true,
          color_icons = true,
          cwd_header = true,
        },
        status = {
          prompt = 'GitStatus❯ ',
          cmd = 'git -c color.status=false --no-optional-locks status --porcelain=v1 -u',
          multiprocess = true,
          file_icons = true,
          color_icons = true,
          previewer = 'git_diff',
          actions = {
            right = false,
            left = false,
            ['ctrl-x'] = { fn = actions.git_reset, reload = true },
            ['ctrl-s'] = { fn = actions.git_stage_unstage, reload = true },
          },
        },
        diff = {
          cmd = 'git --no-pager diff --name-only {ref}',
          ref = 'HEAD',
          preview = 'git diff {ref} {file}',
          file_icons = true,
          color_icons = true,
          fzf_opts = { ['--multi'] = true },
        },
        hunks = {
          cmd = 'git --no-pager diff --color=always {ref}',
          ref = 'HEAD',
          file_icons = true,
          color_icons = true,
          fzf_opts = { ['--multi'] = true, ['--delimiter'] = ':', ['--nth'] = '3..' },
        },
        commits = {
          prompt = 'Commits❯ ',
          cmd = [[git log --color --pretty=format:"%C(yellow)%h%Creset ]]
            .. [[%Cgreen(%><(12)%cr%><|(12))%Creset %s %C(blue)<%an>%Creset"]],
          preview = 'git show --color {1}',
          actions = {
            enter = actions.git_checkout,
            ['ctrl-y'] = { fn = actions.git_yank_commit, exec_silent = true },
          },
        },
        bcommits = {
          prompt = 'BCommits❯ ',
          cmd = [[git log --color --pretty=format:"%C(yellow)%h%Creset ]]
            .. [[%Cgreen(%><(12)%cr%><|(12))%Creset %s %C(blue)<%an>%Creset" {file}]],
          preview = 'git show --color {1} -- {file}',
          actions = {
            enter = actions.git_buf_edit,
            ['ctrl-s'] = actions.git_buf_split,
            ['ctrl-v'] = actions.git_buf_vsplit,
            ['ctrl-t'] = actions.git_buf_tabedit,
            ['ctrl-y'] = { fn = actions.git_yank_commit, exec_silent = true },
          },
        },
        blame = {
          prompt = 'Blame> ',
          cmd = [[git blame --color-lines {file}]],
          preview = 'git show --color {1} -- {file}',
          actions = {
            enter = actions.git_goto_line,
            ['ctrl-s'] = actions.git_buf_split,
            ['ctrl-v'] = actions.git_buf_vsplit,
            ['ctrl-t'] = actions.git_buf_tabedit,
            ['ctrl-y'] = { fn = actions.git_yank_commit, exec_silent = true },
          },
        },
        branches = {
          prompt = 'Branches❯ ',
          cmd = 'git branch --all --color',
          preview = 'git log --graph --pretty=oneline --abbrev-commit --color {1}',
          remotes = 'local',
          actions = {
            enter = actions.git_switch,
            ['ctrl-x'] = { fn = actions.git_branch_del, reload = true },
            ['ctrl-a'] = {
              fn = actions.git_branch_add,
              field_index = '{q}',
              reload = true,
            },
          },
          cmd_add = { 'git', 'checkout', '-b' },
          cmd_del = { 'git', 'branch', '--delete', '--force' },
        },
        tags = {
          prompt = 'Tags> ',
          cmd = [[git for-each-ref --color --sort="-taggerdate" --format ]]
            .. [["%(color:yellow)%(refname:short)%(color:reset) ]]
            .. [[%(color:green)(%(taggerdate:relative))%(color:reset)]]
            .. [[ %(subject) %(color:blue)%(taggername)%(color:reset)" refs/tags]],
          preview = [[git log --graph --color --pretty=format:"%C(yellow)%h%Creset ]]
            .. [[%Cgreen(%><(12)%cr%><|(12))%Creset %s %C(blue)<%an>%Creset" {1}]],
          actions = { enter = actions.git_checkout },
        },
        stash = {
          prompt = 'Stash> ',
          cmd = 'git --no-pager stash list',
          preview = 'git --no-pager stash show --patch --color {1}',
          actions = {
            enter = actions.git_stash_apply,
            ['ctrl-x'] = { fn = actions.git_stash_drop, reload = true },
          },
        },
        icons = {
          R = { icon = 'R', color = 'yellow' },
          C = { icon = 'C', color = 'yellow' },
          T = { icon = 'T', color = 'magenta' },
          ['?'] = { icon = '?', color = 'magenta' },
          M = { icon = '★', color = 'red' },
          D = { icon = '✗', color = 'red' },
          A = { icon = '+', color = 'green' },
        },
      },
      grep = {
        prompt = 'Rg❯ ',
        input_prompt = 'Grep For❯ ',
        multiprocess = true,
        git_icons = false,
        file_icons = true,
        color_icons = true,
        cmd = 'rg --vimgrep',
        grep_opts = '--binary-files=without-match --line-number --recursive --color=auto --perl-regexp -e',
        rg_opts = '--column --line-number --no-heading --color=always --smart-case --max-columns=4096 -e',
        hidden = true,
        follow = false,
        no_ignore = false,
        rg_glob = true,
        glob_flag = '--iglob',
        glob_separator = '%s%-%-',
        multiline = 2,
        no_header = false,
        no_header_i = false,
        actions = {
          ['ctrl-g'] = { actions.grep_lgrep },
          ['ctrl-r'] = { actions.toggle_ignore },
        },
      },
      args = {
        prompt = 'Args❯ ',
        files_only = true,
        actions = { ['ctrl-x'] = { fn = actions.arg_del, reload = true } },
      },
      oldfiles = {
        prompt = 'History❯ ',
        cwd_only = false,
        stat_file = require('fzf-lua').utils.file_is_readable,
        include_current_session = true,
      },
      buffers = {
        prompt = 'Buffers❯ ',
        file_icons = 'mini',
        color_icons = true,
        sort_lastused = true,
        show_unloaded = true,
        cwd_only = false,
        cwd = nil,
        actions = { ['ctrl-x'] = { fn = actions.buf_del, reload = true } },
      },
      tabs = {
        prompt = 'Tabs❯ ',
        tab_title = 'Tab',
        tab_marker = '<<',
        locate = true,
        file_icons = 'mini',
        color_icons = true,
        fzf_opts = { ['--delimiter'] = '[\\):]', ['--with-nth'] = '2..' },
        actions = {
          enter = actions.buf_switch,
          ['ctrl-x'] = { fn = actions.buf_del, reload = true },
        },
      },
      lines = {
        prompt = 'Lines❯ ',
        file_icons = 'mini',
        show_bufname = true,
        show_unloaded = true,
        show_unlisted = false,
        no_term_buffers = true,
        sort_lastused = true,
        winopts = { treesitter = true },
        fzf_opts = {
          ['--multi'] = true,
          ['--delimiter'] = '[\t]',
          ['--tabstop'] = '1',
          ['--tiebreak'] = 'index',
          ['--with-nth'] = '2..',
          ['--nth'] = '4..',
        },
      },
      tags = {
        prompt = 'Tags❯ ',
        ctags_file = nil,
        multiprocess = true,
        file_icons = true,
        color_icons = true,
        rg_opts = '--no-heading --color=always --smart-case',
        grep_opts = '--color=auto --perl-regexp',
        fzf_opts = { ['--tiebreak'] = 'begin' },
        actions = { ['ctrl-g'] = { actions.grep_lgrep } },
        no_header = false,
        no_header_i = false,
      },
      btags = {
        prompt = 'BTags❯ ',
        ctags_file = nil,
        ctags_autogen = true,
        multiprocess = true,
        file_icons = false,
        rg_opts = '--color=never --no-heading',
        grep_opts = '--color=never --perl-regexp',
        fzf_opts = { ['--tiebreak'] = 'begin' },
      },
      colorschemes = {
        prompt = 'Colorschemes❯ ',
        live_preview = true,
        actions = { enter = actions.colorscheme },
        winopts = { height = 0.55, width = 0.30 },
      },
      awesome_colorschemes = {
        prompt = 'Colorschemes❯ ',
        live_preview = true,
        max_threads = 5,
        winopts = { row = 0, col = 0.99, width = 0.50 },
        fzf_opts = {
          ['--multi'] = true,
          ['--delimiter'] = '[:]',
          ['--with-nth'] = '3..',
          ['--tiebreak'] = 'index',
        },
        actions = {
          enter = actions.colorscheme,
          ['ctrl-g'] = { fn = actions.toggle_bg, exec_silent = true },
          ['ctrl-r'] = { fn = actions.cs_update, reload = true },
          ['ctrl-x'] = { fn = actions.cs_delete, reload = true },
        },
      },
      keymaps = {
        prompt = 'Keymaps> ',
        winopts = { preview = { layout = 'vertical' } },
        fzf_opts = { ['--tiebreak'] = 'index' },
        ignore_patterns = { '^<SNR>', '^<Plug>' },
        show_desc = true,
        show_details = true,
        actions = {
          enter = actions.keymap_apply,
          ['ctrl-s'] = actions.keymap_split,
          ['ctrl-v'] = actions.keymap_vsplit,
          ['ctrl-t'] = actions.keymap_tabedit,
        },
      },
      nvim_options = {
        prompt = 'Nvim Options> ',
        separator = '│',
        color_values = true,
        actions = {
          enter = { fn = actions.nvim_opt_edit_local, reload = true },
          ['alt-enter'] = { fn = actions.nvim_opt_edit_global, reload = true },
        },
      },
      quickfix = { file_icons = 'mini', valid_only = false },
      quickfix_stack = { prompt = 'Quickfix Stack> ', marker = '>' },
      lsp = {
        prompt_postfix = '❯ ',
        cwd_only = true,
        async_or_timeout = 5000,
        file_icons = true,
        git_icons = false,
        jump1 = true,
        jump1_action = actions.file_edit,
        includeDeclaration = true,
        symbols = {
          locate = true,
          async_or_timeout = true,
          symbol_style = 1,
          symbol_icons = {
            Array = '󱡠',
            Boolean = '󰨙',
            Class = '󰆧',
            Constant = '󰏿',
            Constructor = '',
            Enum = '',
            EnumMember = '',
            Event = '',
            Field = '',
            File = '󰈙',
            Function = '󰊕',
            Interface = '',
            Key = '󰌋',
            Method = '󰊕',
            Module = '',
            Namespace = '󰦮',
            Null = '󰟢',
            Number = '󰎠',
            Object = '',
            Operator = '󰆕',
            Package = '',
            Property = '',
            String = '',
            Struct = '󰆼',
            TypeParameter = '󰗴',
            Variable = '󰀫',
          },
          symbol_hl = function(s)
            return ('@%s'):format(s:lower())
          end,
          symbol_fmt = function(s, _)
            return ('[%s]'):format(s)
          end,
          child_prefix = true,
          fzf_opts = { ['--tiebreak'] = 'begin' },
        },
        code_actions = {
          prompt = 'Code Actions> ',
          async_or_timeout = 5000,
          previewer = 'codeaction',
        },
        finder = {
          prompt = 'LSP Finder> ',
          file_icons = 'mini',
          color_icons = true,
          async = true,
          silent = true,
          separator = '| ',
          includeDeclaration = true,
          providers = {
            { 'references', prefix = require('fzf-lua').utils.ansi_codes.blue('ref ') },
            {
              'definitions',
              prefix = require('fzf-lua').utils.ansi_codes.green('def '),
            },
            {
              'declarations',
              prefix = require('fzf-lua').utils.ansi_codes.magenta('decl'),
            },
            { 'typedefs', prefix = require('fzf-lua').utils.ansi_codes.red('tdef') },
            {
              'implementations',
              prefix = require('fzf-lua').utils.ansi_codes.green('impl'),
            },
            {
              'incoming_calls',
              prefix = require('fzf-lua').utils.ansi_codes.cyan('in  '),
            },
            {
              'outgoing_calls',
              prefix = require('fzf-lua').utils.ansi_codes.yellow('out '),
            },
          },
        },
      },
      diagnostics = {
        prompt = 'Diagnostics❯ ',
        cwd_only = false,
        file_icons = 'mini',
        git_icons = false,
        color_headings = true,
        diag_icons = true,
        diag_source = true,
        diag_code = true,
        icon_padding = '',
        multiline = 2,
      },
      complete_path = {
        cmd = nil,
        complete = { enter = actions.complete },
        word_pattern = '[^%s"\']*',
      },
      complete_file = {
        cmd = nil,
        file_icons = true,
        color_icons = true,
        word_pattern = nil,
        actions = { enter = actions.complete },
        winopts = { preview = { hidden = true } },
      },
      zoxide = {
        cmd = 'zoxide query --list --score',
        git_root = false,
        formatter = 'path.dirname_first',
        fzf_opts = {
          ['--no-multi'] = true,
          ['--delimiter'] = '[\t]',
          ['--tabstop'] = '4',
          ['--tiebreak'] = 'end,index',
          ['--nth'] = '2..',
        },
        actions = { enter = actions.cd },
      },
      manpages = { previewer = 'man_native' },
      helptags = { previewer = 'help_native' },
      winopts = {
        height = 0.85,
        width = 0.80,
        row = 0.35,
        col = 0.50,
        border = 'rounded',
        backdrop = 60,
        title = 'Title',
        title_pos = 'center',
        title_flags = false,
        fullscreen = false,
        treesitter = {
          enabled = true,
          fzf_colors = { hl = '-1:reverse', ['hl+'] = '-1:reverse' },
        },
        preview = {
          default = 'bat',
          border = 'rounded',
          wrap = vim.o.wrap,
          hidden = false,
          vertical = 'down:45%',
          horizontal = 'right:60%',
          layout = 'flex',
          flip_columns = 100,
          title = true,
          title_pos = 'center',
          scrollbar = 'border',
          scrolloff = -1,
          delay = 20,
          winopts = {
            number = vim.o.number,
            relativenumber = vim.o.relativenumber,
            cursorline = vim.o.cursorline,
            cursorlineopt = vim.o.cursorlineopt,
            cursorcolumn = vim.o.cursorcolumn,
            signcolumn = 'no',
            list = false,
            foldenable = false,
            foldmethod = 'manual',
          },
        },
        on_create = function() end,
        on_close = function() end,
      },
      keymap = {
        builtin = {
          true,
          ['<M-Esc>'] = 'hide',
          ['<F1>'] = 'toggle-help',
          ['<F2>'] = 'toggle-fullscreen',
          ['<F3>'] = 'toggle-preview-wrap',
          ['<F4>'] = 'toggle-preview',
          ['<F5>'] = 'toggle-preview-ccw',
          ['<F6>'] = 'toggle-preview-cw',
          ['<F7>'] = 'toggle-preview-ts-ctx',
          ['<F8>'] = 'preview-ts-ctx-dec',
          ['<F9>'] = 'preview-ts-ctx-inc',
          ['<S-Left>'] = 'preview-reset',
          ['<S-down>'] = 'preview-page-down',
          ['<S-up>'] = 'preview-page-up',
          ['<M-S-down>'] = 'preview-down',
          ['<M-S-up>'] = 'preview-up',
        },
        fzf = {
          true,
          ['ctrl-z'] = 'abort',
          ['ctrl-u'] = 'unix-line-discard',
          ['ctrl-f'] = 'half-page-down',
          ['ctrl-b'] = 'half-page-up',
          ['ctrl-a'] = 'beginning-of-line',
          ['ctrl-e'] = 'end-of-line',
          ['alt-a'] = 'toggle-all',
          ['alt-g'] = 'first',
          ['alt-G'] = 'last',
          f3 = 'toggle-preview-wrap',
          f4 = 'toggle-preview',
          ['shift-down'] = 'preview-page-down',
          ['shift-up'] = 'preview-page-up',
        },
      },
      actions = actions,
      fzf_opts = {
        ['--ansi'] = true,
        ['--info'] = 'inline-right',
        ['--height'] = '100%',
        ['--layout'] = 'reverse',
        ['--border'] = 'none',
        ['--highlight-line'] = true,
      },
      fzf_tmux_opts = { ['-p'] = '80%,80%', ['--margin'] = '0,0' },
      fzf_colors = {
        true,
        ['bg+'] = { 'bg', { 'CursorLine', 'Normal' } },
        ['fg+'] = { 'fg', 'Normal', 'underline' },
        ['hl+'] = { 'fg', 'Statement' },
        bg = { 'bg', 'Normal' },
        fg = { 'fg', 'CursorLine' },
        gutter = '-1',
        header = { 'fg', 'Comment' },
        hl = { 'fg', 'Comment' },
        info = { 'fg', 'PreProc' },
        marker = { 'fg', 'Keyword' },
        pointer = { 'fg', 'Exception' },
        prompt = { 'fg', 'Conditional' },
        spinner = { 'fg', 'Label' },
      },
      hls = { normal = 'Normal', preview_normal = 'Normal' },
      previewers = {
        cat = { cmd = 'cat', args = '-n' },
        bat = { cmd = 'bat', args = '--color=always --style=numbers,changes' },
        head = { cmd = 'head', args = nil },
        git_diff = {
          cmd_deleted = 'git diff --color HEAD --',
          cmd_modified = 'git diff --color HEAD',
          cmd_untracked = 'git diff --color --no-index /dev/null',
        },
        man = { cmd = 'man -c %s | col -bx' },
        builtin = {
          syntax = true,
          syntax_limit_l = 0,
          syntax_limit_b = 1024 * 1024,
          limit_b = 1024 * 1024 * 10,
          treesitter = {
            enabled = true,
            disabled = {},
            context = { max_lines = 1, trim_scope = 'inner' },
          },
          toggle_behavior = 'default',
          extensions = {
            png = { 'chafa', '{file}' },
            svg = { 'chafa', '{file}' },
            jpg = { 'chafa', '{file}' },
          },
          render_markdown = { enabled = true, filetypes = { markdown = true } },
          snacks_image = { enabled = false, render_inline = true },
        },
        codeaction = { diff_opts = { ctxlen = 3 } },
        codeaction_native = {
          diff_opts = { ctxlen = 3 },
          pager = [[delta --width=$COLUMNS --hunk-header-style="omit" --file-style="omit"]],
        },
      },
    })

    require('fzf-lua').register_ui_select()
    vim.api.nvim_set_hl(0, 'FzfLuaBorder', { link = 'FloatBorder' })
  end,
}
-- vim: set ts=2 sts=2 sw=2 et ai si sta:
