---@module 'lazy'
return { ---@type LazySpec
  'ibhagwan/fzf-lua',
  version = false,
  dependencies = { 'nvim-tree/nvim-web-devicons', 'nvim-mini/mini.icons' },
  cond = require('user_api').check.exists.executable('fzf'),
  config = function()
    local actions = require('fzf-lua').actions
    require('fzf-lua').setup({
      actions = actions,
      args = {
        actions = { ['ctrl-x'] = { fn = actions.arg_del, reload = true } },
        files_only = true,
        prompt = 'Args❯ ',
      },
      awesome_colorschemes = {
        actions = {
          ['ctrl-g'] = { exec_silent = true, fn = actions.toggle_bg },
          ['ctrl-r'] = { fn = actions.cs_update, reload = true },
          ['ctrl-x'] = { fn = actions.cs_delete, reload = true },
          enter = actions.colorscheme,
        },
        fzf_opts = { ['--delimiter'] = '[:]', ['--multi'] = true, ['--tiebreak'] = 'index', ['--with-nth'] = '3..' },
        live_preview = true,
        max_threads = 5,
        prompt = 'Colorschemes❯ ',
        winopts = { col = 0.99, row = 0, width = 0.50 },
      },
      btags = {
        ctags_autogen = true,
        file_icons = false,
        fzf_opts = { ['--tiebreak'] = 'begin' },
        grep_opts = '--color=never --perl-regexp',
        multiprocess = true,
        prompt = 'BTags❯ ',
        rg_opts = '--color=never --no-heading',
      },
      buffers = {
        actions = { ['ctrl-x'] = { fn = actions.buf_del, reload = true } },
        color_icons = true,
        cwd = nil,
        cwd_only = false,
        file_icons = 'mini',
        prompt = 'Buffers❯ ',
        show_unloaded = true,
        sort_lastused = true,
      },
      colorschemes = {
        actions = { enter = actions.colorscheme },
        live_preview = true,
        prompt = 'Colorschemes❯ ',
        winopts = { height = 0.55, width = 0.30 },
      },
      complete_file = {
        file_icons = true,
        color_icons = true,
        actions = { enter = actions.complete },
        winopts = { preview = { hidden = true } },
      },
      complete_path = { complete = { enter = actions.complete }, word_pattern = '[^%s"\']*' },
      defaults = { file_icons = 'mini', copen = 'topleft copen' },
      diagnostics = {
        color_headings = true,
        cwd_only = false,
        diag_code = true,
        diag_icons = true,
        diag_source = true,
        file_icons = 'mini',
        git_icons = false,
        icon_padding = '',
        multiline = 2,
        prompt = 'Diagnostics❯ ',
      },
      files = {
        actions = { enter = actions.file_edit },
        cmd = 'rg --files',
        color_icons = true,
        cwd_header = true,
        cwd_prompt = true,
        cwd_prompt_shorten_len = 32,
        cwd_prompt_shorten_val = 1,
        dir_opts = [[/s/b/a:-d]],
        fd_opts = [[--color=never --hidden --type f --type l --exclude .git]],
        file_icons = true,
        find_opts = [[-type f \! -path '*/.git/*']],
        follow = false,
        formatter = 'path.filename_first',
        git_icons = true,
        hidden = true,
        multiprocess = true,
        no_ignore = false,
        path_shorten = true,
        previewer = 'bat',
        prompt = 'Files❯ ',
        rg_opts = [[--color=never --hidden --files -g "!.git"]],
        toggle_follow_flag = '-L',
        toggle_hidden_flag = '--hidden',
        toggle_ignore_flag = '--no-ignore',
      },
      fzf_opts = {
        ['--ansi'] = true,
        ['--border'] = 'none',
        ['--height'] = '100%',
        ['--highlight-line'] = true,
        ['--info'] = 'inline-right',
        ['--layout'] = 'reverse',
      },
      fzf_tmux_opts = { ['-p'] = '80%,80%', ['--margin'] = '0,0' },
      git = {
        bcommits = {
          actions = {
            ['ctrl-s'] = actions.git_buf_split,
            ['ctrl-t'] = actions.git_buf_tabedit,
            ['ctrl-v'] = actions.git_buf_vsplit,
            ['ctrl-y'] = { fn = actions.git_yank_commit, exec_silent = true },
            enter = actions.git_buf_edit,
          },
          cmd = [[git log --color --pretty=format:"%C(yellow)%h%Creset ]]
            .. [[%Cgreen(%><(12)%cr%><|(12))%Creset %s %C(blue)<%an>%Creset" {file}]],
          preview = 'git show --color {1} -- {file}',
          prompt = 'BCommits❯ ',
        },
        blame = {
          actions = {
            ['ctrl-s'] = actions.git_buf_split,
            ['ctrl-t'] = actions.git_buf_tabedit,
            ['ctrl-v'] = actions.git_buf_vsplit,
            ['ctrl-y'] = { fn = actions.git_yank_commit, exec_silent = true },
            enter = actions.git_goto_line,
          },
          cmd = [[git blame --color-lines {file}]],
          preview = 'git show --color {1} -- {file}',
          prompt = 'Blame> ',
        },
        branches = {
          actions = {
            ['ctrl-a'] = { fn = actions.git_branch_add, field_index = '{q}', reload = true },
            ['ctrl-x'] = { fn = actions.git_branch_del, reload = true },
            enter = actions.git_switch,
          },
          cmd = 'git branch --all --color',
          cmd_add = { 'git', 'checkout', '-b' },
          cmd_del = { 'git', 'branch', '--delete', '--force' },
          preview = 'git log --graph --pretty=oneline --abbrev-commit --color {1}',
          prompt = 'Branches❯ ',
          remotes = 'local',
        },
        commits = {
          prompt = 'Commits❯ ',
          cmd = [[git log --color --pretty=format:"%C(yellow)%h%Creset ]]
            .. [[%Cgreen(%><(12)%cr%><|(12))%Creset %s %C(blue)<%an>%Creset"]],
          preview = 'git show --color {1}',
          actions = { enter = actions.git_checkout, ['ctrl-y'] = { fn = actions.git_yank_commit, exec_silent = true } },
        },
        diff = {
          cmd = 'git --no-pager diff --name-only {ref}',
          color_icons = true,
          file_icons = true,
          fzf_opts = { ['--multi'] = true },
          preview = 'git diff {ref} {file}',
          ref = 'HEAD',
        },
        files = {
          cmd = 'git ls-files --exclude-standard',
          color_icons = true,
          cwd_header = true,
          file_icons = true,
          git_icons = true,
          multiprocess = true,
          prompt = 'GitFiles❯ ',
        },
        hunks = {
          cmd = 'git --no-pager diff --color=always {ref}',
          color_icons = true,
          file_icons = true,
          fzf_opts = { ['--multi'] = true, ['--delimiter'] = ':', ['--nth'] = '3..' },
          ref = 'HEAD',
        },
        icons = {
          A = { color = 'green', icon = '+' },
          C = { color = 'yellow', icon = 'C' },
          D = { color = 'red', icon = '✗' },
          M = { color = 'red', icon = '★' },
          R = { color = 'yellow', icon = 'R' },
          T = { color = 'magenta', icon = 'T' },
          ['?'] = { color = 'magenta', icon = '?' },
        },
        stash = {
          actions = { ['ctrl-x'] = { fn = actions.git_stash_drop, reload = true }, enter = actions.git_stash_apply },
          cmd = 'git --no-pager stash list',
          preview = 'git --no-pager stash show --patch --color {1}',
          prompt = 'Stash> ',
        },
        status = {
          actions = {
            ['ctrl-s'] = { fn = actions.git_stage_unstage, reload = true },
            ['ctrl-x'] = { fn = actions.git_reset, reload = true },
            left = false,
            right = false,
          },
          cmd = 'git -c color.status=false --no-optional-locks status --porcelain=v1 -u',
          color_icons = true,
          file_icons = true,
          multiprocess = true,
          previewer = 'git_diff',
          prompt = 'GitStatus❯ ',
        },
        tags = {
          actions = { enter = actions.git_checkout },
          cmd = [[git for-each-ref --color --sort="-taggerdate" --format ]]
            .. [["%(color:yellow)%(refname:short)%(color:reset) ]]
            .. [[%(color:green)(%(taggerdate:relative))%(color:reset)]]
            .. [[ %(subject) %(color:blue)%(taggername)%(color:reset)" refs/tags]],
          preview = [[git log --graph --color --pretty=format:"%C(yellow)%h%Creset ]]
            .. [[%Cgreen(%><(12)%cr%><|(12))%Creset %s %C(blue)<%an>%Creset" {1}]],
          prompt = 'Tags> ',
        },
      },
      globals = { file_icon_padding = '', help_open_win = vim.api.nvim_open_win },
      grep = {
        actions = { ['ctrl-g'] = { actions.grep_lgrep }, ['ctrl-r'] = { actions.toggle_ignore } },
        cmd = 'rg --vimgrep',
        color_icons = true,
        file_icons = true,
        follow = false,
        git_icons = false,
        glob_flag = '--iglob',
        glob_separator = '%s%-%-',
        grep_opts = '--binary-files=without-match --line-number --recursive --color=auto --perl-regexp -e',
        hidden = true,
        input_prompt = 'Grep For❯ ',
        multiline = 2,
        multiprocess = true,
        no_header = false,
        no_header_i = false,
        no_ignore = false,
        prompt = 'Rg❯ ',
        rg_glob = true,
        rg_opts = '--column --line-number --no-heading --color=always --smart-case --max-columns=4096 -e',
      },
      helptags = { previewer = 'help_native' },
      keymap = {
        builtin = {
          true,
          ['<F1>'] = 'toggle-help',
          ['<F2>'] = 'toggle-fullscreen',
          ['<F3>'] = 'toggle-preview-wrap',
          ['<F4>'] = 'toggle-preview',
          ['<F5>'] = 'toggle-preview-ccw',
          ['<F6>'] = 'toggle-preview-cw',
          ['<F7>'] = 'toggle-preview-ts-ctx',
          ['<F8>'] = 'preview-ts-ctx-dec',
          ['<F9>'] = 'preview-ts-ctx-inc',
          ['<M-Esc>'] = 'hide',
          ['<M-S-down>'] = 'preview-down',
          ['<M-S-up>'] = 'preview-up',
          ['<S-Left>'] = 'preview-reset',
          ['<S-down>'] = 'preview-page-down',
          ['<S-up>'] = 'preview-page-up',
        },
        fzf = {
          true,
          ['alt-G'] = 'last',
          ['alt-a'] = 'toggle-all',
          ['alt-g'] = 'first',
          ['ctrl-a'] = 'beginning-of-line',
          ['ctrl-b'] = 'half-page-up',
          ['ctrl-e'] = 'end-of-line',
          ['ctrl-f'] = 'half-page-down',
          ['ctrl-u'] = 'unix-line-discard',
          ['ctrl-z'] = 'abort',
          ['shift-down'] = 'preview-page-down',
          ['shift-up'] = 'preview-page-up',
          f3 = 'toggle-preview-wrap',
          f4 = 'toggle-preview',
        },
      },
      keymaps = {
        actions = {
          ['ctrl-s'] = actions.keymap_split,
          ['ctrl-t'] = actions.keymap_tabedit,
          ['ctrl-v'] = actions.keymap_vsplit,
          enter = actions.keymap_apply,
        },
        fzf_opts = { ['--tiebreak'] = 'index' },
        ignore_patterns = { '^<SNR>', '^<Plug>' },
        prompt = 'Keymaps> ',
        show_desc = true,
        show_details = true,
        winopts = { preview = { layout = 'vertical' } },
      },
      lines = {
        file_icons = 'mini',
        fzf_opts = {
          ['--delimiter'] = '[\t]',
          ['--multi'] = true,
          ['--nth'] = '4..',
          ['--tabstop'] = '1',
          ['--tiebreak'] = 'index',
          ['--with-nth'] = '2..',
        },
        no_term_buffers = true,
        prompt = 'Lines❯ ',
        show_bufname = true,
        show_unlisted = false,
        show_unloaded = true,
        sort_lastused = true,
        winopts = { treesitter = true },
      },
      lsp = {
        async_or_timeout = 5000,
        code_actions = { async_or_timeout = 5000, previewer = 'codeaction', prompt = 'Code Actions> ' },
        cwd_only = true,
        file_icons = true,
        finder = {
          async = true,
          color_icons = true,
          file_icons = 'mini',
          includeDeclaration = true,
          prompt = 'LSP Finder> ',
          providers = {
            { 'references', prefix = require('fzf-lua').utils.ansi_codes.blue('ref ') },
            { 'typedefs', prefix = require('fzf-lua').utils.ansi_codes.red('tdef') },
            { 'declarations', prefix = require('fzf-lua').utils.ansi_codes.magenta('decl') },
            { 'definitions', prefix = require('fzf-lua').utils.ansi_codes.green('def ') },
            { 'implementations', prefix = require('fzf-lua').utils.ansi_codes.green('impl') },
            { 'incoming_calls', prefix = require('fzf-lua').utils.ansi_codes.cyan('in  ') },
            { 'outgoing_calls', prefix = require('fzf-lua').utils.ansi_codes.yellow('out ') },
          },
          separator = '| ',
          silent = true,
        },
        git_icons = false,
        includeDeclaration = true,
        jump1 = true,
        jump1_action = actions.file_edit,
        prompt_postfix = '❯ ',
        symbols = {
          async_or_timeout = true,
          locate = true,
          symbol_fmt = function(s)
            return ('[%s]'):format(s)
          end,
          symbol_hl = function(s)
            return ('@%s'):format(s:lower())
          end,
          symbol_icons = {
            Array = '󱡠',
            Boolean = '󰨙',
            Class = '󰆧',
            Constant = '󰏿',
            Constructor = '',
            Enum = '',
            EnumMember = '',
            Event = '',
            Field = '',
            File = '󰈙',
            Function = '󰊕',
            Interface = '',
            Key = '󰌋',
            Method = '󰊕',
            Module = '',
            Namespace = '󰦮',
            Null = '󰟢',
            Number = '󰎠',
            Object = '',
            Operator = '󰆕',
            Package = '',
            Property = '',
            String = '',
            Struct = '󰆼',
            TypeParameter = '󰗴',
            Variable = '󰀫',
          },
          symbol_style = 1,
          child_prefix = true,
          fzf_opts = { ['--tiebreak'] = 'begin' },
        },
      },
      manpages = { previewer = 'man_native' },
      nvim_options = {
        actions = {
          ['alt-enter'] = { fn = actions.nvim_opt_edit_global, reload = true },
          enter = { fn = actions.nvim_opt_edit_local, reload = true },
        },
        color_values = true,
        prompt = 'Nvim Options> ',
        separator = '│',
      },
      oldfiles = {
        cwd_only = false,
        include_current_session = true,
        prompt = 'History❯ ',
        stat_file = require('fzf-lua').utils.file_is_readable,
      },
      previewers = {
        bat = { cmd = 'bat', args = '--color=always --style=numbers,changes' },
        builtin = {
          extensions = { jpg = { 'chafa', '{file}' }, png = { 'chafa', '{file}' }, svg = { 'chafa', '{file}' } },
          limit_b = 1024 * 1024 * 10,
          render_markdown = { enabled = true, filetypes = { markdown = true } },
          snacks_image = { enabled = false, render_inline = true },
          syntax = true,
          syntax_limit_b = 1024 * 1024,
          syntax_limit_l = 0,
          toggle_behavior = 'default',
          treesitter = { context = { max_lines = 1, trim_scope = 'inner' }, disabled = {}, enabled = true },
        },
        cat = { cmd = 'cat', args = '-n' },
        codeaction = { diff_opts = { ctxlen = 3 } },
        codeaction_native = {
          diff_opts = { ctxlen = 3 },
          pager = [[delta --width=$COLUMNS --hunk-header-style="omit" --file-style="omit"]],
        },
        git_diff = {
          cmd_deleted = 'git diff --color HEAD --',
          cmd_modified = 'git diff --color HEAD',
          cmd_untracked = 'git diff --color --no-index /dev/null',
        },
        head = { cmd = 'head', args = nil },
        man = { cmd = 'man -c %s | col -bx' },
      },
      quickfix = { file_icons = 'mini', valid_only = false },
      quickfix_stack = { marker = '>', prompt = 'Quickfix Stack> ' },
      tabs = {
        actions = { ['ctrl-x'] = { fn = actions.buf_del, reload = true }, enter = actions.buf_switch },
        color_icons = true,
        file_icons = 'mini',
        fzf_opts = { ['--delimiter'] = '[\\):]', ['--with-nth'] = '2..' },
        locate = true,
        prompt = 'Tabs❯ ',
        tab_marker = '<<',
        tab_title = 'Tab',
      },
      tags = {
        actions = { ['ctrl-g'] = { actions.grep_lgrep } },
        color_icons = true,
        ctags_file = nil,
        file_icons = true,
        fzf_opts = { ['--tiebreak'] = 'begin' },
        grep_opts = '--color=auto --perl-regexp',
        multiprocess = true,
        no_header = false,
        no_header_i = false,
        prompt = 'Tags❯ ',
        rg_opts = '--no-heading --color=always --smart-case',
      },
      winopts = {
        backdrop = 60,
        border = 'rounded',
        col = 0.50,
        fullscreen = false,
        height = 0.85,
        preview = {
          border = 'rounded',
          default = 'bat',
          delay = 20,
          flip_columns = 100,
          hidden = false,
          horizontal = 'right:60%',
          layout = 'flex',
          scrollbar = 'border',
          scrolloff = -1,
          title = true,
          title_pos = 'center',
          vertical = 'down:45%',
          winopts = {
            winblend = 40,
            scrolloff = vim.o.scrolloff,
            number = false,
            relativenumber = false,
            cursorline = vim.o.cursorline,
            cursorlineopt = vim.o.cursorlineopt,
            cursorcolumn = vim.o.cursorcolumn,
            signcolumn = 'no',
            list = false,
            foldenable = false,
            foldmethod = 'manual',
          },
          wrap = vim.o.wrap,
        },
        row = 0.35,
        title = 'Title',
        title_flags = false,
        title_pos = 'center',
        treesitter = { enabled = true, fzf_colors = { hl = '-1:reverse', ['hl+'] = '-1:reverse' } },
        width = 0.80,
      },
      zoxide = {
        actions = { enter = actions.cd },
        cmd = 'zoxide query --list --score',
        formatter = 'path.dirname_first',
        fzf_opts = {
          ['--delimiter'] = '[\t]',
          ['--no-multi'] = true,
          ['--nth'] = '2..',
          ['--tabstop'] = '4',
          ['--tiebreak'] = 'end,index',
        },
        git_root = false,
      },
    })

    vim.api.nvim_set_hl(0, 'FzfLuaBorder', { link = 'FloatBorder' })
  end,
}
-- vim: set ts=2 sts=2 sw=2 et ai si sta:
