---@module 'lazy'
return { ---@type LazySpec
  'OXY2DEV/helpview.nvim',
  version = false,
  event = 'VeryLazy',
  cond = not require('user_api').check.in_console(),
  opts = {
    preview = {
      callbacks = {},
      debounce = 150,
      draw_range = { 2 * vim.o.lines, 2 * vim.o.lines },
      edit_range = { 0, 0 },
      enable = true,
      enable_hybrid_mode = true,
      filetypes = { 'help' },
      hybrid_modes = {},
      icon_provider = 'internal',
      ignore_buftypes = { '' },
      ignore_previews = {},
      linewise_hybrid_mode = false,
      max_buf_lines = 500,
      modes = { 'n', 'c', 'no' },
      preview_winopts = { width = math.floor(80) },
      splitview_winopts = { split = 'right' },
    },
    renderers = {},
    vimdoc = {
      arguments = {},
      code_blocks = {},
      headings = {},
      highlight_groups = {},
      horizontal_rules = {},
      inline_codes = {},
      keycodes = {},
      modelines = {},
      notes = {},
      optionlinks = {},
      taglinks = {},
      tags = {},
      urls = {},
    },
  },
}
-- vim: set ts=2 sts=2 sw=2 et ai si sta:
