---@module 'lazy'
return { ---@type LazySpec
  'hedyhli/outline.nvim',
  event = 'VeryLazy',
  version = false,
  config = function()
    require('outline').setup({
      outline_window = {
        auto_close = false,
        auto_jump = false,
        center_on_jump = true,
        focus_on_open = true,
        hide_cursor = false,
        jump_highlight_duration = 300,
        no_provider_message = 'No supported provider...',
        position = 'right', ---@type 'right'|'left'
        relative_width = true,
        show_cursorline = true,
        show_numbers = false,
        show_relative_numbers = false,
        width = 26,
        winhl = '',
        wrap = require('user_api').distro.termux.is_distro(),
      },
      outline_items = {
        auto_update_events = {
          follow = { 'CursorMoved' },
          items = { 'BufEnter', 'BufWinEnter', 'BufWritePost', 'InsertLeave', 'TabEnter', 'WinEnter' },
        },
        auto_set_cursor = true,
        highlight_hovered_item = true,
        show_symbol_details = true,
        show_symbol_lineno = true,
      },
      guides = { enabled = true, markers = { bottom = '└', middle = '├', vertical = '│' } },
      symbol_folding = {
        auto_unfold = { hovered = true, only = true },
        autofold_depth = false,
        markers = { '', '' },
      },
      preview_window = {
        auto_preview = false,
        border = 'single',
        height = 50,
        live = false,
        min_height = 10,
        min_width = 50,
        open_hover_on_preview = false,
        relative_height = true,
        relative_width = true,
        width = 50,
        winblend = 0,
        winhl = 'NormalFloat:',
      },
      keymaps = {
        close = { '<Esc>', 'q' },
        code_actions = 'a',
        down_and_jump = '<C-j>',
        fold = 'h',
        fold_all = 'W',
        fold_reset = 'R',
        fold_toggle = '<Tab>',
        fold_toggle_all = '<S-Tab>',
        goto_and_close = '<S-Cr>',
        goto_location = '<Cr>',
        hover_symbol = '<C-space>',
        peek_location = 'o',
        rename_symbol = 'r',
        restore_location = '<C-g>',
        show_help = '?',
        toggle_preview = 'K',
        unfold = 'l',
        unfold_all = 'E',
        up_and_jump = '<C-k>',
      },
      providers = {
        lsp = { blacklist_clients = {} },
        markdown = { filetypes = { 'markdown' } },
        priority = { 'lsp', 'man', 'markdown' },
      },
      symbols = {
        filter = { 'Package', 'Module', 'Function', 'Class', 'StaticMethod', 'Method', 'Enum' },
        icon_source = 'lspkind',
        icons = {
          Array = { icon = '󰅪', hl = 'Constant' },
          Boolean = { icon = '⊨', hl = 'Boolean' },
          Class = { icon = '𝓒', hl = 'Type' },
          Component = { icon = '󰅴', hl = 'Function' },
          Constant = { icon = '', hl = 'Constant' },
          Constructor = { icon = '', hl = 'Special' },
          Enum = { icon = 'ℰ', hl = 'Type' },
          EnumMember = { icon = '', hl = 'Identifier' },
          Event = { icon = '🗲', hl = 'Type' },
          Field = { icon = '󰆨', hl = 'Identifier' },
          File = { icon = '󰈔', hl = 'Identifier' },
          Fragment = { icon = '󰅴', hl = 'Constant' },
          Function = { icon = '', hl = 'Function' },
          Interface = { icon = '󰜰', hl = 'Type' },
          Key = { icon = '🔐', hl = 'Type' },
          Macro = { icon = ' ', hl = 'Function' },
          Method = { icon = 'ƒ', hl = 'Function' },
          Module = { icon = '󰆧', hl = 'Include' },
          Namespace = { icon = '󰅪', hl = 'Include' },
          Null = { icon = 'NULL', hl = 'Type' },
          Number = { icon = '#', hl = 'Number' },
          Object = { icon = '⦿', hl = 'Type' },
          Operator = { icon = '+', hl = 'Identifier' },
          Package = { icon = '󰏗', hl = 'Include' },
          Parameter = { icon = ' ', hl = 'Identifier' },
          Property = { icon = '', hl = 'Identifier' },
          StaticMethod = { icon = ' ', hl = 'Function' },
          String = { icon = '𝓐', hl = 'String' },
          Struct = { icon = '𝓢', hl = 'Structure' },
          TypeAlias = { icon = ' ', hl = 'Type' },
          TypeParameter = { icon = '𝙏', hl = 'Identifier' },
          Variable = { icon = '', hl = 'Constant' },
        },
      },
    })

    local desc = require('user_api').maps.desc
    require('user_api').config.keymaps.set({
      n = {
        ['<leader>o'] = { group = '+Outline' },
        ['<leader>ot'] = { require('outline').toggle_outline, desc('Toggle Outline') },
      },
    })
  end,
}
-- vim: set ts=2 sts=2 sw=2 et ai si sta:
