---@module 'lazy'
return { ---@type LazySpec
  'folke/snacks.nvim',
  lazy = false,
  version = false,
  priority = 1000,
  config = function()
    local Snacks = require('snacks')
    Snacks.setup({
      statuscolumn = {
        left = { 'mark', 'sign' },
        enabled = true,
        right = { 'fold', 'git' },
        folds = { open = true, git_hl = true },
        git = { patterns = { 'GitSign', 'MiniDiffSign' } },
        refresh = 50,
      },
      scratch = {
        name = 'Scratch',
        ft = function()
          if vim.bo.buftype == '' and vim.bo.filetype ~= '' then
            return vim.bo.filetype
          end
          return 'markdown'
        end,
        root = vim.fs.joinpath(vim.fn.stdpath('data'), 'scratch'),
        autowrite = true,
        filekey = { cwd = true, branch = true, count = true },
        win = { style = 'scratch' },
        ---@type table<string, snacks.win.Config>
        win_by_ft = {
          lua = {
            keys = {
              ['source'] = {
                '<CR>',
                function(self)
                  local buf = self.buf --[[@as integer]]
                  local name = 'scratch.'
                    .. vim.fn.fnamemodify(vim.api.nvim_buf_get_name(buf), ':e')
                  Snacks.debug.run({ buf = self.buf, name = name })
                end,
                desc = 'Source buffer',
                mode = { 'n', 'x' },
              },
            },
          },
        },
      },
      picker = {
        prompt = ' ',
        auto_close = false,
        auto_confirm = false,
        show_delay = 5000,
        limit_live = 10000,
        focus = 'input',
        layout = {
          cycle = true,
          preset = function()
            return vim.o.columns >= 100 and 'default' or 'vertical'
          end,
        },
        matcher = {
          cwd_bonus = true,
          file_pos = true,
          filename_bonus = true,
          frecency = false,
          fuzzy = true,
          history_bonus = false,
          ignorecase = false,
          smartcase = true,
          sort_empty = false,
        },
        sort = { fields = { 'score:desc', '#text', 'idx' } },
        ui_select = true,
        formatters = {
          text = { ft = nil },
          file = {
            filename_first = false,
            truncate = 40,
            filename_only = false,
            icon_width = 2,
            git_status_hl = true,
          },
          selected = { show_always = true, unselected = true },
          severity = { icons = true, level = true, pos = 'left' },
        },
        previewers = {
          diff = { builtin = true, cmd = { 'delta' } },
          git = { builtin = true, args = {} },
          file = { max_size = 1024 * 1024, max_line_length = 500, ft = nil },
          man_pager = nil,
        },
        jump = { jumplist = true, tagstack = true, reuse_win = false, close = true, match = false },
        toggles = {
          follow = 'f',
          hidden = 'h',
          ignored = 'i',
          modified = 'm',
          regex = { icon = 'R', value = false },
        },
        win = {
          input = {
            keys = {
              ['<Esc>'] = { 'close', mode = { 'n', 'i' } },
              G = 'list_bottom',
              ['/'] = 'toggle_focus',
              ['<A-d>'] = { 'inspect', mode = { 'n', 'i' } },
              ['<A-f>'] = { 'toggle_follow', mode = { 'i', 'n' } },
              ['<A-h>'] = { 'toggle_hidden', mode = { 'i', 'n' } },
              ['<A-i>'] = { 'toggle_ignored', mode = { 'i', 'n' } },
              ['<A-m>'] = { 'toggle_maximize', mode = { 'i', 'n' } },
              ['<A-p>'] = { 'toggle_preview', mode = { 'i', 'n' } },
              ['<A-w>'] = { 'cycle_win', mode = { 'i', 'n' } },
              ['<C-Down>'] = { 'history_forward', mode = { 'i', 'n' } },
              ['<C-Up>'] = { 'history_back', mode = { 'i', 'n' } },
              ['<C-a>'] = { 'select_all', mode = { 'n', 'i' } },
              ['<C-b>'] = { 'preview_scroll_up', mode = { 'i', 'n' } },
              ['<C-c>'] = { 'cancel', mode = 'i' },
              ['<C-d>'] = { 'list_scroll_down', mode = { 'i', 'n' } },
              ['<C-f>'] = { 'preview_scroll_down', mode = { 'i', 'n' } },
              ['<C-g>'] = { 'toggle_live', mode = { 'i', 'n' } },
              ['<C-j>'] = { 'list_down', mode = { 'i', 'n' } },
              ['<C-k>'] = { 'list_up', mode = { 'i', 'n' } },
              ['<C-n>'] = { 'list_down', mode = { 'i', 'n' } },
              ['<C-p>'] = { 'list_up', mode = { 'i', 'n' } },
              ['<C-q>'] = { 'qflist', mode = { 'i', 'n' } },
              ['<C-r>#'] = { 'insert_alt', mode = 'i' },
              ['<C-r>%'] = { 'insert_filename', mode = 'i' },
              ['<C-r><C-a>'] = { 'insert_cWORD', mode = 'i' },
              ['<C-r><C-f>'] = { 'insert_file', mode = 'i' },
              ['<C-r><C-l>'] = { 'insert_line', mode = 'i' },
              ['<C-r><C-p>'] = { 'insert_file_full', mode = 'i' },
              ['<C-r><C-w>'] = { 'insert_cword', mode = 'i' },
              ['<C-s>'] = { 'edit_split', mode = { 'i', 'n' } },
              ['<C-t>'] = { 'tab', mode = { 'n', 'i' } },
              ['<C-u>'] = { 'list_scroll_up', mode = { 'i', 'n' } },
              ['<C-v>'] = { 'edit_vsplit', mode = { 'i', 'n' } },
              ['<C-w>'] = { '<c-s-w>', mode = { 'i' }, expr = true, desc = 'delete word' },
              ['<C-w>H'] = 'layout_left',
              ['<C-w>J'] = 'layout_bottom',
              ['<C-w>K'] = 'layout_top',
              ['<C-w>L'] = 'layout_right',
              ['<CR>'] = { 'confirm', mode = { 'n', 'i' } },
              ['<Down>'] = { 'list_down', mode = { 'i', 'n' } },
              ['<S-Tab>'] = { 'select_and_prev', mode = { 'i', 'n' } },
              ['<Tab>'] = { 'select_and_next', mode = { 'i', 'n' } },
              ['<Up>'] = { 'list_up', mode = { 'i', 'n' } },
              ['?'] = 'toggle_help_input',
              gg = 'list_top',
              j = 'list_down',
              k = 'list_up',
              q = 'close',
            },
            b = { minipairs_disable = true },
          },
          list = {
            keys = {
              G = 'list_bottom',
              ['/'] = 'toggle_focus',
              ['<A-d>'] = 'inspect',
              ['<A-f>'] = 'toggle_follow',
              ['<A-h>'] = 'toggle_hidden',
              ['<A-i>'] = 'toggle_ignored',
              ['<A-m>'] = 'toggle_maximize',
              ['<A-p>'] = 'toggle_preview',
              ['<A-w>'] = 'cycle_win',
              ['<C-a>'] = 'select_all',
              ['<C-b>'] = 'preview_scroll_up',
              ['<C-d>'] = 'list_scroll_down',
              ['<C-f>'] = 'preview_scroll_down',
              ['<C-j>'] = 'list_down',
              ['<C-k>'] = 'list_up',
              ['<C-n>'] = 'list_down',
              ['<C-p>'] = 'list_up',
              ['<C-q>'] = 'qflist',
              ['<C-s>'] = 'edit_split',
              ['<C-t>'] = 'tab',
              ['<C-u>'] = 'list_scroll_up',
              ['<C-v>'] = 'edit_vsplit',
              ['<C-w>H'] = 'layout_left',
              ['<C-w>J'] = 'layout_bottom',
              ['<C-w>K'] = 'layout_top',
              ['<C-w>L'] = 'layout_right',
              ['<CR>'] = 'confirm',
              ['<Down>'] = 'list_down',
              ['<Esc>'] = 'cancel',
              ['<S-Tab>'] = { 'select_and_prev', mode = { 'n', 'x' } },
              ['<Tab>'] = { 'select_and_next', mode = { 'n', 'x' } },
              ['<Up>'] = 'list_up',
              ['?'] = 'toggle_help_list',
              gg = 'list_top',
              i = 'focus_input',
              j = 'list_down',
              k = 'list_up',
              q = 'close',
              zb = 'list_scroll_bottom',
              zt = 'list_scroll_top',
              zz = 'list_scroll_center',
            },
            wo = { conceallevel = 2, concealcursor = 'nvc' },
          },
          preview = {
            keys = { ['<A-w>'] = 'cycle_win', ['<Esc>'] = 'cancel', i = 'focus_input', q = 'close' },
          },
        },
        icons = {
          files = { enabled = true, dir = '󰉋 ', dir_open = '󰝰 ', file = '󰈔 ' },
          keymaps = { nowait = '󰓅 ' },
          tree = { vertical = '│ ', middle = '├╴', last = '└╴' },
          undo = { saved = ' ' },
          ui = {
            live = '󰐰 ',
            hidden = 'h',
            ignored = 'i',
            follow = 'f',
            selected = '● ',
            unselected = '○ ',
          },
          git = {
            enabled = true,
            commit = '󰜘 ',
            staged = '●',
            added = '',
            deleted = '',
            ignored = ' ',
            modified = '○',
            renamed = '',
            unmerged = ' ',
            untracked = '?',
          },
          diagnostics = { Error = ' ', Warn = ' ', Hint = ' ', Info = ' ' },
          lsp = { unavailable = '', enabled = ' ', disabled = ' ', attached = '󰖩 ' },
          kinds = {
            Array = ' ',
            Boolean = '󰨙 ',
            Class = ' ',
            Color = ' ',
            Control = ' ',
            Collapsed = ' ',
            Constant = '󰏿 ',
            Constructor = ' ',
            Copilot = ' ',
            Enum = ' ',
            EnumMember = ' ',
            Event = ' ',
            Field = ' ',
            File = ' ',
            Folder = ' ',
            Function = '󰊕 ',
            Interface = ' ',
            Key = ' ',
            Keyword = ' ',
            Method = '󰊕 ',
            Module = ' ',
            Namespace = '󰦮 ',
            Null = ' ',
            Number = '󰎠 ',
            Object = ' ',
            Operator = ' ',
            Package = ' ',
            Property = ' ',
            Reference = ' ',
            Snippet = '󱄽 ',
            String = ' ',
            Struct = '󰆼 ',
            Text = ' ',
            TypeParameter = ' ',
            Unit = ' ',
            Unknown = ' ',
            Value = ' ',
            Variable = '󰀫 ',
          },
        },
        db = { sqlite3_path = nil },
        debug = {
          scores = false,
          leaks = false,
          explorer = false,
          files = false,
          grep = false,
          proc = false,
          extmarks = false,
        },
      },
      scroll = {
        animate = { duration = { step = 10, total = 200 }, easing = 'linear' },
        animate_repeat = { delay = 100, duration = { step = 5, total = 50 }, easing = 'linear' },
        filter = function(bufnr)
          return vim.g.snacks_scroll ~= false
            and vim.b[bufnr].snacks_scroll ~= false
            and vim.bo[bufnr].buftype ~= 'terminal'
        end,
      },
      notifier = {
        timeout = 3000,
        width = { min = 40, max = 0.45 },
        height = { min = 1, max = 0.6 },
        margin = { top = 0, right = 0, bottom = 0 },
        padding = true,
        gap = 1,
        sort = { 'level', 'added' },
        level = vim.log.levels.DEBUG,
        icons = {
          error = ' ',
          warn = ' ',
          info = ' ',
          debug = ' ',
          trace = ' ',
        },
        keep = function()
          return vim.fn.getcmdpos() > 0
        end,
        style = 'fancy', ---@type snacks.notifier.style
        top_down = true,
        date_format = '%R',
        more_format = ' ↓ %d lines ',
        refresh = 50,
      },
      styles = {
        scratch = {
          width = 100,
          height = 30,
          bo = { buftype = '', buflisted = false, bufhidden = 'hide', swapfile = false },
          minimal = true,
          noautocmd = false,
          zindex = 20,
          wo = { winhighlight = 'NormalFloat:Normal' },
          footer_keys = true,
          border = true,
        },
        notification = {
          border = true,
          zindex = 100,
          ft = 'markdown',
          wo = { winblend = 5, wrap = false, conceallevel = 2, colorcolumn = '' },
          bo = { filetype = 'snacks_notif' },
        },
      },
      gh = {},
      input = { enabled = true },
      layout = { enabled = true },
      notify = { enabled = true },
    })

    Snacks.scroll.enable()

    local Picker = Snacks.picker
    local desc = require('user_api.maps').desc
    require('user_api.config').keymaps.set({
      n = {
        ['<leader>.'] = { group = 'Scratch' },
        ['<leader>S'] = { group = 'Snacks' },
        ['<leader>Ss'] = { group = 'Search' },
        ['<leader>.,'] = { Snacks.scratch.select, desc('Select Scratch Buffer') },
        ['<leader>..'] = { Snacks.scratch.open, desc('Toggle Scratch Buffer') },
        ['<leader><CR>'] = { Picker.command_history, desc('Command History') },
        ['<leader>S.'] = { Picker.command_history, desc('Command History') },
        ['<leader>SM'] = { Picker.man, desc('Man Pages') },
        ['<leader>Sb'] = { Picker.buffers, desc('Buffers') },
        ['<leader>Sd'] = { Picker.diagnostics, desc('Diagnostics') },
        ['<leader>Sf'] = { Picker.explorer, desc('File Explorer') },
        ['<leader>Sh'] = { Picker.help, desc('Help Pages') },
        ['<leader>Sl'] = { Picker.lazy, desc('Lazy') },
        ['<leader>Sn'] = { Picker.notifications, desc('Notifications') },
        ['<leader>SsC'] = { Picker.colorschemes, desc('Colorschemes') },
        ['<leader>SsH'] = { Picker.highlights, desc('Highlights') },
        ['<leader>Ssa'] = { Picker.autocmds, desc('Autocmds') },
        ['<leader>Ssc'] = { Picker.commands, desc('Commands') },
        ['<leader>Ssh'] = { Picker.search_history, desc('Search History') },
        ['<leader>Ssi'] = { Picker.icons, desc('Icons') },
        ['<leader>Ssk'] = { Picker.keymaps, desc('Keymaps') },
        ['<leader>Ssl'] = { Picker.lines, desc('Lines') },
        ['<leader>lD'] = { Picker.diagnostics, desc('Diagnostics') },
        ['<leader>lG'] = { Picker.lsp_declarations, desc('Goto Declaration (Snacks)') },
        ['<leader>lI'] = { Picker.lsp_implementations, desc('Goto Implementation (Snacks)') },
        ['<leader>ld'] = { Picker.lsp_definitions, desc('Goto Definition (Snacks)') },
        ['<leader>lr'] = { Picker.lsp_references, nowait = true, desc('References (Snacks)') },
        ['<leader>lwS'] = { Picker.lsp_workspace_symbols, desc = 'LSP Workspace Symbols (Snacks)' },
        ['<leader>lws'] = { Picker.lsp_symbols, desc('LSP Symbols (Snacks)') },
        ['<leader>ly'] = { Picker.lsp_type_definitions, desc('Goto Type Definition (Snacks)') },
        ['<leader>us'] = { Picker.colorschemes, desc('Colorschemes (Snacks)') },
        gD = { Picker.lsp_declarations, desc('Goto Declaration') },
        gI = { Picker.lsp_implementations, desc('Goto Implementation') },
        gai = { Picker.lsp_incoming_calls, desc('Calls Incoming') },
        gao = { Picker.lsp_outgoing_calls, desc('Calls Outgoing') },
        gd = { Picker.lsp_definitions, desc('Goto Definition') },
        gr = { Picker.lsp_references, nowait = true, desc('References') },
        gy = { Picker.lsp_type_definitions, desc('Goto Type Definition') },
      },
    })
  end,
}
-- vim: set ts=2 sts=2 sw=2 et ai si sta:
