---@module 'lazy'
return { ---@type LazySpec
  'folke/trouble.nvim',
  version = false,
  event = 'LspAttach',
  config = function()
    require('trouble').setup({
      auto_close = false,
      auto_jump = true,
      auto_open = false,
      auto_preview = true,
      auto_refresh = true,
      focus = true,
      follow = true,
      icons = {
        folder_closed = ' ',
        folder_open = ' ',
        indent = {
          fold_closed = ' ',
          fold_open = ' ',
          last = '╰╴',
          middle = '├╴',
          top = '│ ',
          ws = '  ',
        },
        kinds = {
          Array = ' ',
          Boolean = '󰨙 ',
          Class = ' ',
          Constant = '󰏿 ',
          Constructor = ' ',
          Enum = ' ',
          EnumMember = ' ',
          Event = ' ',
          Field = ' ',
          File = ' ',
          Function = '󰊕 ',
          Interface = ' ',
          Key = ' ',
          Method = '󰊕 ',
          Module = ' ',
          Namespace = '󰦮 ',
          Null = ' ',
          Number = '󰎠 ',
          Object = ' ',
          Operator = ' ',
          Package = ' ',
          Property = ' ',
          String = ' ',
          Struct = '󰆼 ',
          TypeParameter = ' ',
          Variable = '󰀫 ',
        },
      },
      indent_guides = true,
      keys = {
        P = 'toggle_preview',
        R = 'toggle_refresh',
        ['<C-s>'] = 'jump_split',
        ['<C-v>'] = 'jump_vsplit',
        ['<CR>'] = 'jump',
        ['<Esc>'] = 'cancel',
        ['?'] = 'help',
        ['[['] = 'prev',
        [']]'] = 'next',
        ['{'] = 'prev',
        ['}'] = 'next',
        gb = {
          action = function(view)
            view:filter({ buf = vim.api.nvim_get_current_buf() }, { toggle = true })
          end,
          desc = 'Toggle Current Buffer Filter',
        },
        i = 'inspect',
        j = 'next',
        k = 'prev',
        o = 'jump_close',
        p = 'preview',
        q = 'close',
        r = 'refresh',
        s = {
          action = function(view)
            local f = view:get_filter('severity')
            local severity = (f and (f.filter.severity + 1) or 1) % 5
            view:filter({ severity = severity }, {
              id = 'severity',
              template = '{hl:Title}Filter:{hl} {severity}',
              del = severity == 0,
            })
          end,
          desc = 'Toggle Severity Filter',
        },
        zA = 'fold_toggle_recursive',
        zC = 'fold_close_recursive',
        zM = 'fold_close_all',
        zN = 'fold_enable',
        zO = 'fold_open_recursive',
        zR = 'fold_open_all',
        zX = 'fold_update_all',
        za = 'fold_toggle',
        zc = 'fold_close',
        zi = 'fold_toggle_enable',
        zm = 'fold_more',
        zn = 'fold_disable',
        zo = 'fold_open',
        zr = 'fold_reduce',
        zx = 'fold_update',
      },
      max_items = 200,
      modes = {
        diagnostics = {
          auto_close = false,
          auto_jump = true,
          auto_open = false,
          auto_preview = true,
          auto_refresh = true,
          focus = true,
          follow = true,
          indent_guides = true,
          mode = 'diagnostics',
        },
        diagnostics_buffer = { mode = 'diagnostics', filter = { buf = 0 } },
        lsp_base = { params = { include_current = true } },
        lsp_references = { params = { include_declaration = true } },
        preview_float = {
          mode = 'diagnostics',
          preview = {
            border = 'rounded',
            position = { 0, -2 },
            relative = 'editor',
            size = { width = 0.3, height = 0.3 },
            title = 'Preview',
            title_pos = 'center',
            type = 'float',
            zindex = 200,
          },
        },
        symbols = {
          desc = 'document symbols',
          filter = {
            ['not'] = { ft = 'lua', kind = 'Package' },
            any = {
              ft = { 'help', 'markdown' },
              kind = {
                'Class',
                'Constructor',
                'Enum',
                'Field',
                'Function',
                'Interface',
                'Method',
                'Module',
                'Namespace',
                'Package',
                'Property',
                'Struct',
                'Trait',
              },
            },
          },
          focus = true,
          mode = 'lsp_document_symbols',
          win = { position = 'right' },
        },
        test = { mode = 'diagnostics', preview = { position = 'right', relative = 'win', size = 0.3, type = 'split' } },
      },
      multiline = true,
      open_no_results = false,
      pinned = true,
      preview = { type = 'main', scratch = true },
      restore = true,
      throttle = { follow = 100, preview = { debounce = true, ms = 100 }, refresh = 20, render = 10, update = 10 },
      warn_no_results = false,
      win = {},
    })

    local desc = require('user_api').maps.desc
    require('user_api').config.keymaps.set({
      n = { ---@type AllMaps
        ['<leader>lx'] = { group = '+Trouble' },
        ['<leader>lxL'] = { ':Trouble loclist toggle<CR>', desc('Toggle Loclist') },
        ['<leader>lxS'] = { ':Trouble symbols toggle focus=true<CR>', desc('Toggle Focus Symbols') },
        ['<leader>lxX'] = {
          function()
            vim.cmd.Trouble({
              args = { 'diagnostics', 'toggle', ('filter.buf=%s'):format(vim.api.nvim_get_current_buf()) },
            })
          end,
          desc('Toggle Buffer-Local Diagnostics'),
        },
        ['<leader>lxl'] = { ':Trouble lsp toggle focus=false<CR>', desc('Toggle LSP') },
        ['<leader>lxr'] = { ':Trouble lsp_references<CR>', desc('Toggle LSP References') },
        ['<leader>lxs'] = { ':Trouble symbols toggle focus=false<CR>', desc('Toggle Symbols') },
        ['<leader>lxx'] = { ':Trouble diagnostics toggle<CR>', desc('Toggle Global Diagnostics') },
      },
    })
  end,
}
-- vim: set ts=2 sts=2 sw=2 et ai si sta:
