---@module 'lazy'

---@type LazySpec
return {
    'folke/ts-comments.nvim',
    cond = not require('user_api.check').in_console(),
    opts = {
        lang = {
            astro = '<!-- %s -->',
            axaml = '<!-- %s -->',
            blueprint = '// %s',
            c = '// %s',
            c_sharp = '// %s',
            clojure = { ';; %s', '; %s' },
            cpp = '// %s',
            cs_project = '<!-- %s -->',
            cue = '// %s',
            fsharp = '// %s',
            fsharp_project = '<!-- %s -->',
            gleam = '// %s',
            glimmer = '{{! %s }}',
            graphql = '# %s',
            handlebars = '{{! %s }}',
            hcl = '# %s',
            html = '<!-- %s -->',
            hyprlang = '# %s',
            ini = '; %s',
            ipynb = '# %s',
            javascript = {
                '// %s',
                '/* %s */',
                call_expression = '// %s',
                jsx_attribute = '// %s',
                jsx_element = '{/* %s */}',
                jsx_fragment = '{/* %s */}',
                spread_element = '// %s',
                statement_block = '// %s',
            },
            kdl = '// %s',
            php = '// %s',
            rego = '# %s',
            rescript = '// %s',
            rust = { '// %s', '/* %s */' },
            sql = '-- %s',
            styled = '/* %s */',
            svelte = '<!-- %s -->',
            templ = { '// %s', component_block = '<!-- %s -->' },
            terraform = '# %s',
            tsx = {
                '// %s',
                '/* %s */',
                call_expression = '// %s',
                jsx_attribute = '// %s',
                jsx_element = '{/* %s */}',
                jsx_fragment = '{/* %s */}',
                spread_element = '// %s',
                statement_block = '// %s',
            },
            twig = '{# %s #}',
            typescript = { '// %s', '/* %s */' }, -- langs can have multiple commentstrings
            vue = '<!-- %s -->',
            xaml = '<!-- %s -->',
        },
    },
    enabled = vim.fn.has('nvim-0.10.0') == 1,
}
--- vim:ts=4:sts=4:sw=4:et:ai:si:sta:
